__report = {
  info: {
    file: "src\\emergencyServices.js",
    fileShort: "src\\emergencyServices.js",
    fileSafe: "src_emergencyServices_js",
    link: "files/src_emergencyServices_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 3,
      cyclomaticDensity: 15,
      halstead: {
        bugs: 0.329,
        difficulty: 17.091,
        effort: 16859.34,
        length: 167,
        time: 936.63,
        vocabulary: 60,
        volume: 986.451,
        operands: { distinct: 44, total: 94, identifiers: ["__stripped__"] },
        operators: { distinct: 16, total: 73, identifiers: ["__stripped__"] },
      },
      params: 9,
      sloc: { logical: 20, physical: 47 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./position", type: "esm" },
      { line: 11, path: "./tileValues", type: "esm" },
    ],
    errors: [],
    lineEnd: 47,
    lineStart: 1,
    maintainability: 69.821,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.005,
          difficulty: 1,
          effort: 15.51,
          length: 6,
          time: 0.862,
          vocabulary: 6,
          volume: 15.51,
          operands: { distinct: 4, total: 4, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 1, physical: 20 },
        errors: [],
        lineEnd: 32,
        lineStart: 13,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.168,
          difficulty: 9.9,
          effort: 4986.222,
          length: 99,
          time: 277.012,
          vocabulary: 34,
          volume: 503.659,
          operands: { distinct: 25, total: 55, identifiers: ["__stripped__"] },
          operators: { distinct: 9, total: 44, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 12, physical: 18 },
        errors: [],
        lineEnd: 31,
        lineStart: 14,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.015,
          difficulty: 1.429,
          effort: 63.399,
          length: 14,
          time: 3.522,
          vocabulary: 9,
          volume: 44.379,
          operands: { distinct: 7, total: 10, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 4, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 43,
        lineStart: 40,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 1.667,
      cyclomaticDensity: 58.333,
      halstead: {
        bugs: 0.063,
        difficulty: 4.11,
        effort: 1688.377,
        length: 39.667,
        time: 93.799,
        vocabulary: 16.333,
        volume: 187.849,
        operands: { distinct: 12, total: 23 },
        operators: { distinct: 4.333, total: 16.667 },
      },
      params: 3,
      sloc: { logical: 5, physical: 14 },
    },
    module: "src\\emergencyServices.js",
  },
  jshint: { messages: [] },
};
