__report = {
  info: {
    file: "src\\buildingTool.js",
    fileShort: "src\\buildingTool.js",
    fileSafe: "src_buildingTool_js",
    link: "files/src_buildingTool_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 17,
      cyclomaticDensity: 26.984,
      halstead: {
        bugs: 0.825,
        difficulty: 49.719,
        effort: 122981.445,
        length: 388,
        time: 6832.302,
        vocabulary: 83,
        volume: 2473.515,
        operands: { distinct: 57, total: 218, identifiers: ["__stripped__"] },
        operators: { distinct: 26, total: 170, identifiers: ["__stripped__"] },
      },
      params: 14,
      sloc: { logical: 63, physical: 115 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./connectingTool", type: "esm" },
      { line: 11, path: "./tileFlags", type: "esm" },
      { line: 12, path: "./tileValues", type: "esm" },
      { line: 13, path: "./tileUtils", type: "esm" },
    ],
    errors: [],
    lineEnd: 115,
    lineStart: 1,
    maintainability: 59.421,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.031,
          difficulty: 3.563,
          effort: 332.754,
          length: 27,
          time: 18.486,
          vocabulary: 11,
          volume: 93.405,
          operands: { distinct: 8, total: 19, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 8, identifiers: ["__stripped__"] },
        },
        params: 5,
        sloc: { logical: 4, physical: 6 },
        errors: [],
        lineEnd: 20,
        lineStart: 15,
        name: "<anonymous>",
      },
      {
        cyclomatic: 7,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.161,
          difficulty: 18,
          effort: 8678.747,
          length: 94,
          time: 482.153,
          vocabulary: 35,
          volume: 482.153,
          operands: { distinct: 21, total: 54, identifiers: ["__stripped__"] },
          operators: { distinct: 14, total: 40, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 21, physical: 25 },
        errors: [],
        lineEnd: 47,
        lineStart: 23,
        name: "<anonymous>",
      },
      {
        cyclomatic: 10,
        cyclomaticDensity: 43.478,
        halstead: {
          bugs: 0.239,
          difficulty: 21.6,
          effort: 15518.742,
          length: 135,
          time: 862.152,
          vocabulary: 40,
          volume: 718.46,
          operands: { distinct: 25, total: 72, identifiers: ["__stripped__"] },
          operators: { distinct: 15, total: 63, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 23, physical: 39 },
        errors: [],
        lineEnd: 88,
        lineStart: 50,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 22.222,
        halstead: {
          bugs: 0.064,
          difficulty: 10.8,
          effort: 2071.619,
          length: 46,
          time: 115.09,
          vocabulary: 18,
          volume: 191.817,
          operands: { distinct: 10, total: 27, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 19, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 9, physical: 17 },
        errors: [],
        lineEnd: 107,
        lineStart: 91,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.014,
          difficulty: 2.25,
          effort: 92.72,
          length: 13,
          time: 5.151,
          vocabulary: 9,
          volume: 41.209,
          operands: { distinct: 6, total: 9, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 4, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 112,
        lineStart: 110,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 4.2,
      cyclomaticDensity: 44.807,
      halstead: {
        bugs: 0.102,
        difficulty: 11.242,
        effort: 5338.916,
        length: 63,
        time: 296.606,
        vocabulary: 22.6,
        volume: 305.409,
        operands: { distinct: 14, total: 36.2 },
        operators: { distinct: 8.6, total: 26.8 },
      },
      params: 2.8,
      sloc: { logical: 11.6, physical: 18 },
    },
    module: "src\\buildingTool.js",
  },
  jshint: { messages: [] },
};
