__report = {
  info: {
    file: "src\\budget.js",
    fileShort: "src\\budget.js",
    fileSafe: "src_budget_js",
    link: "files/src_budget_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 22,
      cyclomaticDensity: 13.333,
      halstead: {
        bugs: 2.867,
        difficulty: 77.16,
        effort: 663605.247,
        length: 1182,
        time: 36866.958,
        vocabulary: 155,
        volume: 8600.379,
        operands: { distinct: 125, total: 643, identifiers: ["__stripped__"] },
        operators: { distinct: 30, total: 539, identifiers: ["__stripped__"] },
      },
      params: 12,
      sloc: { logical: 165, physical: 284 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./eventEmitter", type: "esm" },
      { line: 11, path: "./messages", type: "esm" },
      { line: 12, path: "./miscUtils", type: "esm" },
    ],
    errors: [],
    lineEnd: 284,
    lineStart: 1,
    maintainability: 60.08,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 4.545,
        halstead: {
          bugs: 0.215,
          difficulty: 5.455,
          effort: 3520.882,
          length: 123,
          time: 195.605,
          vocabulary: 38,
          volume: 645.495,
          operands: { distinct: 33, total: 72, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 51, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 22, physical: 32 },
        errors: [],
        lineEnd: 58,
        lineStart: 27,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.033,
          difficulty: 6.429,
          effort: 642.291,
          length: 27,
          time: 35.683,
          vocabulary: 13,
          volume: 99.912,
          operands: { distinct: 7, total: 15, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 12, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 4 },
        errors: [],
        lineEnd: 68,
        lineStart: 65,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.068,
          difficulty: 7.269,
          effort: 1476.603,
          length: 47,
          time: 82.034,
          vocabulary: 20,
          volume: 203.131,
          operands: { distinct: 13, total: 27, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 20, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 6, physical: 7 },
        errors: [],
        lineEnd: 77,
        lineStart: 71,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.017,
          difficulty: 2.5,
          effort: 126.797,
          length: 16,
          time: 7.044,
          vocabulary: 9,
          volume: 50.719,
          operands: { distinct: 6, total: 10, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 6, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 83,
        lineStart: 80,
        name: "<anonymous>",
      },
      {
        cyclomatic: 8,
        cyclomaticDensity: 17.021,
        halstead: {
          bugs: 0.465,
          difficulty: 44.788,
          effort: 62459.751,
          length: 257,
          time: 3469.986,
          vocabulary: 43,
          volume: 1394.55,
          operands: { distinct: 26, total: 137, identifiers: ["__stripped__"] },
          operators: {
            distinct: 17,
            total: 120,
            identifiers: ["__stripped__"],
          },
        },
        params: 0,
        sloc: { logical: 47, physical: 59 },
        errors: [],
        lineEnd: 153,
        lineStart: 95,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.005,
          difficulty: 1.5,
          effort: 23.265,
          length: 6,
          time: 1.292,
          vocabulary: 6,
          volume: 15.51,
          operands: { distinct: 3, total: 3, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 3, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 159,
        lineStart: 157,
        name: "<anonymous>",
      },
      {
        cyclomatic: 6,
        cyclomaticDensity: 31.579,
        halstead: {
          bugs: 0.207,
          difficulty: 15.12,
          effort: 9373.265,
          length: 119,
          time: 520.737,
          vocabulary: 37,
          volume: 619.925,
          operands: { distinct: 25, total: 63, identifiers: ["__stripped__"] },
          operators: { distinct: 12, total: 56, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 19, physical: 31 },
        errors: [],
        lineEnd: 192,
        lineStart: 162,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 16.667,
        halstead: {
          bugs: 0.064,
          difficulty: 8.273,
          effort: 1586.846,
          length: 46,
          time: 88.158,
          vocabulary: 18,
          volume: 191.817,
          operands: { distinct: 11, total: 26, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 20, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 6, physical: 9 },
        errors: [],
        lineEnd: 203,
        lineStart: 195,
        name: "<anonymous>",
      },
      {
        cyclomatic: 4,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.223,
          difficulty: 13.125,
          effort: 8799.514,
          length: 141,
          time: 488.862,
          vocabulary: 27,
          volume: 670.439,
          operands: { distinct: 20, total: 75, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 66, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 12, physical: 20 },
        errors: [],
        lineEnd: 225,
        lineStart: 206,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 14.286,
        halstead: {
          bugs: 0.252,
          difficulty: 11.629,
          effort: 8799.665,
          length: 137,
          time: 488.87,
          vocabulary: 46,
          volume: 756.728,
          operands: { distinct: 35, total: 74, identifiers: ["__stripped__"] },
          operators: { distinct: 11, total: 63, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 14, physical: 24 },
        errors: [],
        lineEnd: 251,
        lineStart: 228,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 66.667,
        halstead: {
          bugs: 0.013,
          difficulty: 5.833,
          effort: 227.5,
          length: 13,
          time: 12.639,
          vocabulary: 8,
          volume: 39,
          operands: { distinct: 3, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 3, physical: 6 },
        errors: [],
        lineEnd: 259,
        lineStart: 254,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.055,
          difficulty: 6.9,
          effort: 1131.6,
          length: 41,
          time: 62.867,
          vocabulary: 16,
          volume: 164,
          operands: { distinct: 10, total: 23, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 18, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 6, physical: 10 },
        errors: [],
        lineEnd: 271,
        lineStart: 262,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.009,
          difficulty: 2.25,
          effort: 63.165,
          length: 10,
          time: 3.509,
          vocabulary: 7,
          volume: 28.074,
          operands: { distinct: 4, total: 6, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 4, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 276,
        lineStart: 274,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.02,
          difficulty: 3.429,
          effort: 202.996,
          length: 16,
          time: 11.278,
          vocabulary: 13,
          volume: 59.207,
          operands: { distinct: 7, total: 8, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 8, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 281,
        lineStart: 279,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 2.5,
      cyclomaticDensity: 47.674,
      halstead: {
        bugs: 0.118,
        difficulty: 9.607,
        effort: 7031.01,
        length: 71.357,
        time: 390.612,
        vocabulary: 21.5,
        volume: 352.75,
        operands: { distinct: 14.5, total: 39 },
        operators: { distinct: 7, total: 32.357 },
      },
      params: 0.857,
      sloc: { logical: 10.286, physical: 15.357 },
    },
    module: "src\\budget.js",
  },
  jshint: { messages: [] },
};
