__report = {
  info: {
    file: "src\\tileUtils.js",
    fileShort: "src\\tileUtils.js",
    fileSafe: "src_tileUtils_js",
    link: "files/src_tileUtils_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 23,
      cyclomaticDensity: 42.593,
      halstead: {
        bugs: 0.996,
        difficulty: 45.871,
        effort: 137072.227,
        length: 465,
        time: 7615.124,
        vocabulary: 86,
        volume: 2988.213,
        operands: { distinct: 62, total: 237, identifiers: ["__stripped__"] },
        operators: { distinct: 24, total: 228, identifiers: ["__stripped__"] },
      },
      params: 16,
      sloc: { logical: 54, physical: 127 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./random", type: "esm" },
      { line: 11, path: "./tile", type: "esm" },
      { line: 12, path: "./tileFlags", type: "esm" },
      { line: 13, path: "./tileValues", type: "esm" },
    ],
    errors: [],
    lineEnd: 127,
    lineStart: 1,
    maintainability: 87.638,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.003,
          difficulty: 1,
          effort: 8,
          length: 4,
          time: 0.444,
          vocabulary: 4,
          volume: 8,
          operands: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 7 },
        errors: [],
        lineEnd: 21,
        lineStart: 15,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 66.667,
        halstead: {
          bugs: 0.022,
          difficulty: 5,
          effort: 322.647,
          length: 18,
          time: 17.925,
          vocabulary: 12,
          volume: 64.529,
          operands: { distinct: 6, total: 10, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 8, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 3, physical: 5 },
        errors: [],
        lineEnd: 20,
        lineStart: 16,
        name: "<anonymous>",
      },
      {
        cyclomatic: 6,
        cyclomaticDensity: 600,
        halstead: {
          bugs: 0.057,
          difficulty: 8.556,
          effort: 1471.556,
          length: 43,
          time: 81.753,
          vocabulary: 16,
          volume: 172,
          operands: { distinct: 9, total: 22, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 21, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 5 },
        errors: [],
        lineEnd: 28,
        lineStart: 24,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 200,
        halstead: {
          bugs: 0.014,
          difficulty: 4.375,
          effort: 180.289,
          length: 13,
          time: 10.016,
          vocabulary: 9,
          volume: 41.209,
          operands: { distinct: 4, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 33,
        lineStart: 31,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 200,
        halstead: {
          bugs: 0.009,
          difficulty: 3.333,
          effort: 93.578,
          length: 10,
          time: 5.199,
          vocabulary: 7,
          volume: 28.074,
          operands: { distinct: 3, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 38,
        lineStart: 36,
        name: "<anonymous>",
      },
      {
        cyclomatic: 4,
        cyclomaticDensity: 400,
        halstead: {
          bugs: 0.03,
          difficulty: 6.5,
          effort: 582.556,
          length: 25,
          time: 32.364,
          vocabulary: 12,
          volume: 89.624,
          operands: { distinct: 6, total: 13, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 12, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 4 },
        errors: [],
        lineEnd: 44,
        lineStart: 41,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 200,
        halstead: {
          bugs: 0.014,
          difficulty: 4.375,
          effort: 180.289,
          length: 13,
          time: 10.016,
          vocabulary: 9,
          volume: 41.209,
          operands: { distinct: 4, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 49,
        lineStart: 47,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 200,
        halstead: {
          bugs: 0.014,
          difficulty: 4.375,
          effort: 180.289,
          length: 13,
          time: 10.016,
          vocabulary: 9,
          volume: 41.209,
          operands: { distinct: 4, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 54,
        lineStart: 52,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 200,
        halstead: {
          bugs: 0.014,
          difficulty: 4.375,
          effort: 180.289,
          length: 13,
          time: 10.016,
          vocabulary: 9,
          volume: 41.209,
          operands: { distinct: 4, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 59,
        lineStart: 57,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 200,
        halstead: {
          bugs: 0.009,
          difficulty: 3.333,
          effort: 93.578,
          length: 10,
          time: 5.199,
          vocabulary: 7,
          volume: 28.074,
          operands: { distinct: 3, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 64,
        lineStart: 62,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 200,
        halstead: {
          bugs: 0.014,
          difficulty: 4.375,
          effort: 180.289,
          length: 13,
          time: 10.016,
          vocabulary: 9,
          volume: 41.209,
          operands: { distinct: 4, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 69,
        lineStart: 67,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 200,
        halstead: {
          bugs: 0.014,
          difficulty: 4.375,
          effort: 180.289,
          length: 13,
          time: 10.016,
          vocabulary: 9,
          volume: 41.209,
          operands: { distinct: 4, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 74,
        lineStart: 72,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 200,
        halstead: {
          bugs: 0.014,
          difficulty: 4.375,
          effort: 180.289,
          length: 13,
          time: 10.016,
          vocabulary: 9,
          volume: 41.209,
          operands: { distinct: 4, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 79,
        lineStart: 77,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 200,
        halstead: {
          bugs: 0.009,
          difficulty: 3.333,
          effort: 93.578,
          length: 10,
          time: 5.199,
          vocabulary: 7,
          volume: 28.074,
          operands: { distinct: 3, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 84,
        lineStart: 82,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 200,
        halstead: {
          bugs: 0.014,
          difficulty: 4.375,
          effort: 180.289,
          length: 13,
          time: 10.016,
          vocabulary: 9,
          volume: 41.209,
          operands: { distinct: 4, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 89,
        lineStart: 87,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 300,
        halstead: {
          bugs: 0.029,
          difficulty: 6.857,
          effort: 589.382,
          length: 22,
          time: 32.743,
          vocabulary: 15,
          volume: 85.952,
          operands: { distinct: 7, total: 12, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 10, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 94,
        lineStart: 92,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.017,
          difficulty: 3,
          effort: 155.418,
          length: 14,
          time: 8.634,
          vocabulary: 13,
          volume: 51.806,
          operands: { distinct: 7, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 7, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 99,
        lineStart: 97,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.017,
          difficulty: 3,
          effort: 155.418,
          length: 14,
          time: 8.634,
          vocabulary: 13,
          volume: 51.806,
          operands: { distinct: 7, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 7, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 104,
        lineStart: 102,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 2.222,
      cyclomaticDensity: 214.815,
      halstead: {
        bugs: 0.017,
        difficulty: 4.384,
        effort: 278.224,
        length: 15.222,
        time: 15.457,
        vocabulary: 9.889,
        volume: 52.089,
        operands: { distinct: 4.722, total: 8 },
        operators: { distinct: 5.167, total: 7.222 },
      },
      params: 0.889,
      sloc: { logical: 1.111, physical: 3.5 },
    },
    module: "src\\tileUtils.js",
  },
  jshint: { messages: [] },
};
