__report = {
  info: {
    file: "src\\game.js",
    fileShort: "src\\game.js",
    fileSafe: "src_game_js",
    link: "files/src_game_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 82,
      cyclomaticDensity: 19.57,
      halstead: {
        bugs: 8.947,
        difficulty: 69.895,
        effort: 1876146.23,
        length: 3040,
        time: 104230.346,
        vocabulary: 455,
        volume: 26842.357,
        operands: { distinct: 419, total: 1627, identifiers: ["__stripped__"] },
        operators: { distinct: 36, total: 1413, identifiers: ["__stripped__"] },
      },
      params: 21,
      sloc: { logical: 419, physical: 707 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./baseTool", type: "esm" },
      { line: 11, path: "./budgetWindow", type: "esm" },
      { line: 12, path: "./config", type: "esm" },
      { line: 13, path: "./congratsWindow", type: "esm" },
      { line: 14, path: "./debugWindow", type: "esm" },
      { line: 15, path: "./disasterWindow", type: "esm" },
      { line: 16, path: "./evaluationWindow", type: "esm" },
      { line: 17, path: "./gameCanvas", type: "esm" },
      { line: 18, path: "./gameMap", type: "esm" },
      { line: 19, path: "./infoBar", type: "esm" },
      { line: 20, path: "./inputStatus", type: "esm" },
      { line: 21, path: "./messages", type: "esm" },
      { line: 22, path: "./monsterTV", type: "esm" },
      { line: 23, path: "./nagWindow", type: "esm" },
      { line: 24, path: "./notification", type: "esm" },
      { line: 25, path: "./queryWindow", type: "esm" },
      { line: 26, path: "./random", type: "esm" },
      { line: 27, path: "./rci", type: "esm" },
      { line: 28, path: "./saveWindow", type: "esm" },
      { line: 29, path: "./screenshotLinkWindow", type: "esm" },
      { line: 30, path: "./screenshotWindow", type: "esm" },
      { line: 31, path: "./settingsWindow", type: "esm" },
      { line: 32, path: "./simulation", type: "esm" },
      { line: 33, path: "./storage", type: "esm" },
      { line: 34, path: "./text", type: "esm" },
      { line: 35, path: "./touchWarnWindow", type: "esm" },
    ],
    errors: [],
    lineEnd: 707,
    lineStart: 1,
    maintainability: 58.154,
    methods: [
      {
        cyclomatic: 9,
        cyclomaticDensity: 8.911,
        halstead: {
          bugs: 2.363,
          difficulty: 21.223,
          effort: 150483.184,
          length: 925,
          time: 8360.177,
          vocabulary: 203,
          volume: 7090.436,
          operands: {
            distinct: 188,
            total: 532,
            identifiers: ["__stripped__"],
          },
          operators: {
            distinct: 15,
            total: 393,
            identifiers: ["__stripped__"],
          },
        },
        params: 6,
        sloc: { logical: 101, physical: 202 },
        errors: [],
        lineEnd: 241,
        lineStart: 40,
        name: "Game",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.018,
          difficulty: 1.929,
          effort: 102.505,
          length: 16,
          time: 5.695,
          vocabulary: 10,
          volume: 53.151,
          operands: { distinct: 7, total: 9, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 7, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 3, physical: 5 },
        errors: [],
        lineEnd: 84,
        lineStart: 80,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.007,
          difficulty: 1.5,
          effort: 33.688,
          length: 8,
          time: 1.872,
          vocabulary: 7,
          volume: 22.459,
          operands: { distinct: 4, total: 4, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 4, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 1, physical: 11 },
        errors: [],
        lineEnd: 96,
        lineStart: 86,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 40,
        halstead: {
          bugs: 0.033,
          difficulty: 5.625,
          effort: 556.826,
          length: 26,
          time: 30.935,
          vocabulary: 14,
          volume: 98.991,
          operands: { distinct: 8, total: 15, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 11, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 5, physical: 9 },
        errors: [],
        lineEnd: 95,
        lineStart: 87,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.006,
          difficulty: 1.5,
          effort: 27.142,
          length: 7,
          time: 1.508,
          vocabulary: 6,
          volume: 18.095,
          operands: { distinct: 3, total: 3, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 4, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 109,
        lineStart: 107,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 9.091,
        halstead: {
          bugs: 0.173,
          difficulty: 12,
          effort: 6241.565,
          length: 106,
          time: 346.754,
          vocabulary: 30,
          volume: 520.13,
          operands: { distinct: 21, total: 56, identifiers: ["__stripped__"] },
          operators: { distinct: 9, total: 50, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 11, physical: 15 },
        errors: [],
        lineEnd: 130,
        lineStart: 116,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 20,
        halstead: {
          bugs: 0.044,
          difficulty: 4,
          effort: 533.75,
          length: 32,
          time: 29.653,
          vocabulary: 18,
          volume: 133.438,
          operands: { distinct: 12, total: 16, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 16, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 5, physical: 4 },
        errors: [],
        lineEnd: 150,
        lineStart: 147,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 16.667,
        halstead: {
          bugs: 0.04,
          difficulty: 5.667,
          effort: 686.31,
          length: 31,
          time: 38.128,
          vocabulary: 15,
          volume: 121.114,
          operands: { distinct: 9, total: 17, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 14, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 6, physical: 7 },
        errors: [],
        lineEnd: 250,
        lineStart: 244,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.03,
          difficulty: 3.429,
          effort: 307.516,
          length: 27,
          time: 17.084,
          vocabulary: 10,
          volume: 89.692,
          operands: { distinct: 7, total: 16, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 11, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 6 },
        errors: [],
        lineEnd: 258,
        lineStart: 253,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 14.286,
        halstead: {
          bugs: 0.053,
          difficulty: 2.969,
          effort: 469.429,
          length: 36,
          time: 26.079,
          vocabulary: 21,
          volume: 158.123,
          operands: { distinct: 16, total: 19, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 17, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 7, physical: 8 },
        errors: [],
        lineEnd: 274,
        lineStart: 267,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.007,
          difficulty: 1,
          effort: 22.459,
          length: 8,
          time: 1.248,
          vocabulary: 7,
          volume: 22.459,
          operands: { distinct: 5, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 3, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 270,
        lineStart: 268,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.009,
          difficulty: 1.2,
          effort: 33.688,
          length: 10,
          time: 1.872,
          vocabulary: 7,
          volume: 28.074,
          operands: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 4, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 280,
        lineStart: 277,
        name: "<anonymous>",
      },
      {
        cyclomatic: 4,
        cyclomaticDensity: 80,
        halstead: {
          bugs: 0.052,
          difficulty: 5.455,
          effort: 847.22,
          length: 38,
          time: 47.068,
          vocabulary: 17,
          volume: 155.324,
          operands: { distinct: 11, total: 20, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 18, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 5, physical: 6 },
        errors: [],
        lineEnd: 288,
        lineStart: 283,
        name: "<anonymous>",
      },
      {
        cyclomatic: 8,
        cyclomaticDensity: 38.095,
        halstead: {
          bugs: 0.15,
          difficulty: 9.429,
          effort: 4256.377,
          length: 92,
          time: 236.465,
          vocabulary: 30,
          volume: 451.434,
          operands: { distinct: 21, total: 44, identifiers: ["__stripped__"] },
          operators: { distinct: 9, total: 48, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 21, physical: 31 },
        errors: [],
        lineEnd: 321,
        lineStart: 291,
        name: "<anonymous>",
      },
      {
        cyclomatic: 6,
        cyclomaticDensity: 28.571,
        halstead: {
          bugs: 0.181,
          difficulty: 10.607,
          effort: 5774.491,
          length: 103,
          time: 320.805,
          vocabulary: 39,
          volume: 544.396,
          operands: { distinct: 28, total: 54, identifiers: ["__stripped__"] },
          operators: { distinct: 11, total: 49, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 21, physical: 29 },
        errors: [],
        lineEnd: 352,
        lineStart: 324,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 27.273,
        halstead: {
          bugs: 0.088,
          difficulty: 8.842,
          effort: 2321.693,
          length: 53,
          time: 128.983,
          vocabulary: 31,
          volume: 262.572,
          operands: { distinct: 19, total: 28, identifiers: ["__stripped__"] },
          operators: { distinct: 12, total: 25, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 11, physical: 16 },
        errors: [],
        lineEnd: 370,
        lineStart: 355,
        name: "<anonymous>",
      },
      {
        cyclomatic: 4,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.091,
          difficulty: 7.294,
          effort: 1998.497,
          length: 59,
          time: 111.028,
          vocabulary: 25,
          volume: 273.988,
          operands: { distinct: 17, total: 31, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 28, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 12, physical: 16 },
        errors: [],
        lineEnd: 388,
        lineStart: 373,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 27.273,
        halstead: {
          bugs: 0.138,
          difficulty: 11.059,
          effort: 4570.647,
          length: 89,
          time: 253.925,
          vocabulary: 25,
          volume: 413.303,
          operands: { distinct: 17, total: 47, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 42, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 11, physical: 16 },
        errors: [],
        lineEnd: 406,
        lineStart: 391,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.01,
          difficulty: 3,
          effort: 90,
          length: 10,
          time: 5,
          vocabulary: 8,
          volume: 30,
          operands: { distinct: 4, total: 6, identifiers: ["__stripped__"] },
          operators: { distinct: 4, total: 4, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 2, physical: 20 },
        errors: [],
        lineEnd: 428,
        lineStart: 409,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 30,
        halstead: {
          bugs: 0.081,
          difficulty: 7.467,
          effort: 1823.9,
          length: 54,
          time: 101.328,
          vocabulary: 23,
          volume: 244.272,
          operands: { distinct: 15, total: 28, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 26, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 10, physical: 16 },
        errors: [],
        lineEnd: 427,
        lineStart: 412,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.008,
          difficulty: 1.875,
          effort: 47.374,
          length: 9,
          time: 2.632,
          vocabulary: 7,
          volume: 25.266,
          operands: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 4, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 440,
        lineStart: 437,
        name: "<anonymous>",
      },
      {
        cyclomatic: 4,
        cyclomaticDensity: 21.053,
        halstead: {
          bugs: 0.208,
          difficulty: 11.569,
          effort: 7203.597,
          length: 117,
          time: 400.2,
          vocabulary: 40,
          volume: 622.666,
          operands: { distinct: 29, total: 61, identifiers: ["__stripped__"] },
          operators: { distinct: 11, total: 56, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 19, physical: 32 },
        errors: [],
        lineEnd: 474,
        lineStart: 443,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.023,
          difficulty: 2.063,
          effort: 142.702,
          length: 20,
          time: 7.928,
          vocabulary: 11,
          volume: 69.189,
          operands: { distinct: 8, total: 11, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 9, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 4, physical: 6 },
        errors: [],
        lineEnd: 482,
        lineStart: 477,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 40,
        halstead: {
          bugs: 0.038,
          difficulty: 6.857,
          effort: 786.608,
          length: 31,
          time: 43.7,
          vocabulary: 13,
          volume: 114.714,
          operands: { distinct: 7, total: 16, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 15, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 5, physical: 11 },
        errors: [],
        lineEnd: 495,
        lineStart: 485,
        name: "<anonymous>",
      },
      {
        cyclomatic: 8,
        cyclomaticDensity: 42.105,
        halstead: {
          bugs: 0.139,
          difficulty: 7.333,
          effort: 3059.698,
          length: 91,
          time: 169.983,
          vocabulary: 24,
          volume: 417.232,
          operands: { distinct: 18, total: 44, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 47, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 19, physical: 24 },
        errors: [],
        lineEnd: 521,
        lineStart: 498,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.035,
          difficulty: 1.846,
          effort: 192,
          length: 26,
          time: 10.667,
          vocabulary: 16,
          volume: 104,
          operands: { distinct: 13, total: 16, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 10, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 6 },
        errors: [],
        lineEnd: 530,
        lineStart: 525,
        name: "<anonymous>",
      },
      {
        cyclomatic: 23,
        cyclomaticDensity: 41.818,
        halstead: {
          bugs: 0.629,
          difficulty: 27.368,
          effort: 51625.128,
          length: 301,
          time: 2868.063,
          vocabulary: 77,
          volume: 1886.303,
          operands: { distinct: 57, total: 156, identifiers: ["__stripped__"] },
          operators: {
            distinct: 20,
            total: 145,
            identifiers: ["__stripped__"],
          },
        },
        params: 1,
        sloc: { logical: 55, physical: 83 },
        errors: [],
        lineEnd: 615,
        lineStart: 533,
        name: "<anonymous>",
      },
      {
        cyclomatic: 5,
        cyclomaticDensity: 45.455,
        halstead: {
          bugs: 0.16,
          difficulty: 17.105,
          effort: 8210.526,
          length: 96,
          time: 456.14,
          vocabulary: 32,
          volume: 480,
          operands: { distinct: 19, total: 50, identifiers: ["__stripped__"] },
          operators: { distinct: 13, total: 46, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 11, physical: 23 },
        errors: [],
        lineEnd: 640,
        lineStart: 618,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 40,
        halstead: {
          bugs: 0.061,
          difficulty: 5.133,
          effort: 938.562,
          length: 41,
          time: 52.142,
          vocabulary: 22,
          volume: 182.837,
          operands: { distinct: 15, total: 22, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 19, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 5, physical: 9 },
        errors: [],
        lineEnd: 651,
        lineStart: 643,
        name: "<anonymous>",
      },
      {
        cyclomatic: 4,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.084,
          difficulty: 6.125,
          effort: 1551.582,
          length: 56,
          time: 86.199,
          vocabulary: 23,
          volume: 253.319,
          operands: { distinct: 16, total: 28, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 28, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 8, physical: 18 },
        errors: [],
        lineEnd: 671,
        lineStart: 654,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 30,
        halstead: {
          bugs: 0.118,
          difficulty: 9.188,
          effort: 3241.698,
          length: 78,
          time: 180.094,
          vocabulary: 23,
          volume: 352.838,
          operands: { distinct: 16, total: 42, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 36, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 10, physical: 17 },
        errors: [],
        lineEnd: 690,
        lineStart: 674,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 42.857,
        halstead: {
          bugs: 0.092,
          difficulty: 11,
          effort: 3050.585,
          length: 59,
          time: 169.477,
          vocabulary: 26,
          volume: 277.326,
          operands: { distinct: 15, total: 30, identifiers: ["__stripped__"] },
          operators: { distinct: 11, total: 29, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 7, physical: 12 },
        errors: [],
        lineEnd: 704,
        lineStart: 693,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 3.469,
      cyclomaticDensity: 41.723,
      halstead: {
        bugs: 0.162,
        difficulty: 7.27,
        effort: 8163.467,
        length: 82.969,
        time: 453.526,
        vocabulary: 26.875,
        volume: 484.911,
        operands: { distinct: 19.813, total: 44.906 },
        operators: { distinct: 7.063, total: 38.063 },
      },
      params: 0.656,
      sloc: { logical: 12.156, physical: 21 },
    },
    module: "src\\game.js",
  },
  jshint: { messages: [] },
};
