__report = {
  info: {
    file: "src\\queryTool.js",
    fileShort: "src\\queryTool.js",
    fileSafe: "src_queryTool_js",
    link: "files/src_queryTool_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 28,
      cyclomaticDensity: 31.111,
      halstead: {
        bugs: 2.168,
        difficulty: 48.595,
        effort: 316073.065,
        length: 871,
        time: 17559.615,
        vocabulary: 177,
        volume: 6504.284,
        operands: { distinct: 148, total: 496, identifiers: ["__stripped__"] },
        operators: { distinct: 29, total: 375, identifiers: ["__stripped__"] },
      },
      params: 24,
      sloc: { logical: 90, physical: 148 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./baseTool", type: "esm" },
      { line: 11, path: "./config", type: "esm" },
      { line: 12, path: "./eventEmitter", type: "esm" },
      { line: 13, path: "./messages", type: "esm" },
      { line: 14, path: "./text", type: "esm" },
      { line: 15, path: "./tileValues", type: "esm" },
    ],
    errors: [],
    lineEnd: 148,
    lineStart: 1,
    maintainability: 62.238,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.008,
          difficulty: 1.4,
          effort: 35.373,
          length: 9,
          time: 1.965,
          vocabulary: 7,
          volume: 25.266,
          operands: { distinct: 5, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 20,
        lineStart: 18,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.077,
          difficulty: 6.824,
          effort: 1584.374,
          length: 50,
          time: 88.021,
          vocabulary: 25,
          volume: 232.193,
          operands: { distinct: 17, total: 29, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 21, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 6, physical: 8 },
        errors: [],
        lineEnd: 30,
        lineStart: 23,
        name: "<anonymous>",
      },
      {
        cyclomatic: 6,
        cyclomaticDensity: 42.857,
        halstead: {
          bugs: 0.117,
          difficulty: 6.783,
          effort: 2385.769,
          length: 71,
          time: 132.543,
          vocabulary: 31,
          volume: 351.748,
          operands: { distinct: 23, total: 39, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 32, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 14, physical: 16 },
        errors: [],
        lineEnd: 48,
        lineStart: 33,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.077,
          difficulty: 6.824,
          effort: 1584.374,
          length: 50,
          time: 88.021,
          vocabulary: 25,
          volume: 232.193,
          operands: { distinct: 17, total: 29, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 21, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 6, physical: 8 },
        errors: [],
        lineEnd: 58,
        lineStart: 51,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.077,
          difficulty: 6.824,
          effort: 1584.374,
          length: 50,
          time: 88.021,
          vocabulary: 25,
          volume: 232.193,
          operands: { distinct: 17, total: 29, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 21, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 6, physical: 8 },
        errors: [],
        lineEnd: 68,
        lineStart: 61,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.077,
          difficulty: 6.824,
          effort: 1584.374,
          length: 50,
          time: 88.021,
          vocabulary: 25,
          volume: 232.193,
          operands: { distinct: 17, total: 29, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 21, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 6, physical: 8 },
        errors: [],
        lineEnd: 78,
        lineStart: 71,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.181,
          difficulty: 8.217,
          effort: 4471.032,
          length: 112,
          time: 248.391,
          vocabulary: 29,
          volume: 544.094,
          operands: { distinct: 23, total: 63, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 49, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 9, physical: 11 },
        errors: [],
        lineEnd: 91,
        lineStart: 81,
        name: "<anonymous>",
      },
      {
        cyclomatic: 5,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.299,
          difficulty: 14,
          effort: 12569.863,
          length: 152,
          time: 698.326,
          vocabulary: 60,
          volume: 897.847,
          operands: { distinct: 46, total: 92, identifiers: ["__stripped__"] },
          operators: { distinct: 14, total: 60, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 10, physical: 22 },
        errors: [],
        lineEnd: 115,
        lineStart: 94,
        name: "<anonymous>",
      },
      {
        cyclomatic: 9,
        cyclomaticDensity: 40.909,
        halstead: {
          bugs: 0.401,
          difficulty: 13.152,
          effort: 15810.524,
          length: 207,
          time: 878.362,
          vocabulary: 56,
          volume: 1202.122,
          operands: { distinct: 46, total: 121, identifiers: ["__stripped__"] },
          operators: { distinct: 10, total: 86, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 22, physical: 28 },
        errors: [],
        lineEnd: 145,
        lineStart: 118,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 4,
      cyclomaticDensity: 51.9,
      halstead: {
        bugs: 0.146,
        difficulty: 7.872,
        effort: 4623.34,
        length: 83.444,
        time: 256.852,
        vocabulary: 31.444,
        volume: 438.872,
        operands: { distinct: 23.444, total: 48.667 },
        operators: { distinct: 8, total: 34.778 },
      },
      params: 2.667,
      sloc: { logical: 8.889, physical: 12.444 },
    },
    module: "src\\queryTool.js",
  },
  jshint: { messages: [] },
};
