__report = {
  info: {
    file: "src\\rci.js",
    fileShort: "src\\rci.js",
    fileSafe: "src_rci_js",
    link: "files/src_rci_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 13,
      cyclomaticDensity: 18.31,
      halstead: {
        bugs: 1.523,
        difficulty: 45.313,
        effort: 207046.989,
        length: 640,
        time: 11502.611,
        vocabulary: 141,
        volume: 4569.313,
        operands: { distinct: 112, total: 350, identifiers: ["__stripped__"] },
        operators: { distinct: 29, total: 290, identifiers: ["__stripped__"] },
      },
      params: 11,
      sloc: { logical: 71, physical: 135 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./messages", type: "esm" },
      { line: 11, path: "./miscUtils", type: "esm" },
    ],
    errors: [],
    lineEnd: 135,
    lineStart: 1,
    maintainability: 59.591,
    methods: [
      {
        cyclomatic: 9,
        cyclomaticDensity: 32.143,
        halstead: {
          bugs: 0.379,
          difficulty: 20.415,
          effort: 23198.385,
          length: 188,
          time: 1288.799,
          vocabulary: 66,
          volume: 1136.346,
          operands: { distinct: 47, total: 101, identifiers: ["__stripped__"] },
          operators: { distinct: 19, total: 87, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 28, physical: 45 },
        errors: [],
        lineEnd: 57,
        lineStart: 13,
        name: "RCI",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.018,
          difficulty: 1.571,
          effort: 84.682,
          length: 17,
          time: 4.705,
          vocabulary: 9,
          volume: 53.889,
          operands: { distinct: 7, total: 11, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 6, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 62,
        lineStart: 60,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 16.667,
        halstead: {
          bugs: 0.085,
          difficulty: 7.615,
          effort: 1940.976,
          length: 60,
          time: 107.832,
          vocabulary: 19,
          volume: 254.876,
          operands: { distinct: 13, total: 33, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 27, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 6, physical: 13 },
        errors: [],
        lineEnd: 77,
        lineStart: 65,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 37.5,
        halstead: {
          bugs: 0.201,
          difficulty: 16.38,
          effort: 9885.521,
          length: 115,
          time: 549.196,
          vocabulary: 38,
          volume: 603.512,
          operands: { distinct: 25, total: 63, identifiers: ["__stripped__"] },
          operators: { distinct: 13, total: 52, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 8, physical: 15 },
        errors: [],
        lineEnd: 94,
        lineStart: 80,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 16.667,
        halstead: {
          bugs: 0.121,
          difficulty: 8,
          effort: 2914.789,
          length: 75,
          time: 161.933,
          vocabulary: 29,
          volume: 364.349,
          operands: { distinct: 21, total: 42, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 33, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 6, physical: 11 },
        errors: [],
        lineEnd: 107,
        lineStart: 97,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 20,
        halstead: {
          bugs: 0.204,
          difficulty: 11.034,
          effort: 6765.315,
          length: 116,
          time: 375.851,
          vocabulary: 39,
          volume: 613.107,
          operands: { distinct: 29, total: 64, identifiers: ["__stripped__"] },
          operators: { distinct: 10, total: 52, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 15, physical: 21 },
        errors: [],
        lineEnd: 130,
        lineStart: 110,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 3,
      cyclomaticDensity: 37.163,
      halstead: {
        bugs: 0.168,
        difficulty: 10.836,
        effort: 7464.945,
        length: 95.167,
        time: 414.719,
        vocabulary: 33.333,
        volume: 504.346,
        operands: { distinct: 23.667, total: 52.333 },
        operators: { distinct: 9.667, total: 42.833 },
      },
      params: 1.833,
      sloc: { logical: 10.667, physical: 18 },
    },
    module: "src\\rci.js",
  },
  jshint: { messages: [] },
};
