__report = {
  info: {
    file: "src\\connector.js",
    fileShort: "src\\connector.js",
    fileSafe: "src_connector_js",
    link: "files/src_connector_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 87,
      cyclomaticDensity: 78.378,
      halstead: {
        bugs: 2.776,
        difficulty: 109.558,
        effort: 912541.837,
        length: 1219,
        time: 50696.769,
        vocabulary: 114,
        volume: 8329.293,
        operands: { distinct: 86, total: 673, identifiers: ["__stripped__"] },
        operators: { distinct: 28, total: 546, identifiers: ["__stripped__"] },
      },
      params: 8,
      sloc: { logical: 111, physical: 228 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./tileFlags", type: "esm" },
      { line: 11, path: "./tileUtils", type: "esm" },
      { line: 12, path: "./tileValues", type: "esm" },
    ],
    errors: [],
    lineEnd: 228,
    lineStart: 1,
    maintainability: 45.458,
    methods: [
      {
        cyclomatic: 79,
        cyclomaticDensity: 98.75,
        halstead: {
          bugs: 1.662,
          difficulty: 86.87,
          effort: 433131.652,
          length: 831,
          time: 24062.87,
          vocabulary: 64,
          volume: 4986,
          operands: { distinct: 46, total: 444, identifiers: ["__stripped__"] },
          operators: {
            distinct: 18,
            total: 387,
            identifiers: ["__stripped__"],
          },
        },
        params: 2,
        sloc: { logical: 80, physical: 137 },
        errors: [],
        lineEnd: 172,
        lineStart: 36,
        name: "<anonymous>",
      },
      {
        cyclomatic: 5,
        cyclomaticDensity: 55.556,
        halstead: {
          bugs: 0.091,
          difficulty: 15.556,
          effort: 4231.111,
          length: 68,
          time: 235.062,
          vocabulary: 16,
          volume: 272,
          operands: { distinct: 9, total: 40, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 28, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 9, physical: 15 },
        errors: [],
        lineEnd: 189,
        lineStart: 175,
        name: "<anonymous>",
      },
      {
        cyclomatic: 5,
        cyclomaticDensity: 45.455,
        halstead: {
          bugs: 0.124,
          difficulty: 30.375,
          effort: 11298.258,
          length: 91,
          time: 627.681,
          vocabulary: 17,
          volume: 371.959,
          operands: { distinct: 8, total: 54, identifiers: ["__stripped__"] },
          operators: { distinct: 9, total: 37, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 11, physical: 19 },
        errors: [],
        lineEnd: 210,
        lineStart: 192,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.024,
          difficulty: 4.2,
          effort: 302.4,
          length: 24,
          time: 16.8,
          vocabulary: 8,
          volume: 72,
          operands: { distinct: 5, total: 14, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 10, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 6 },
        errors: [],
        lineEnd: 225,
        lineStart: 220,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 22.5,
      cyclomaticDensity: 56.19,
      halstead: {
        bugs: 0.475,
        difficulty: 34.25,
        effort: 112240.855,
        length: 253.5,
        time: 6235.603,
        vocabulary: 26.25,
        volume: 1425.49,
        operands: { distinct: 17, total: 138 },
        operators: { distinct: 9.25, total: 115.5 },
      },
      params: 2,
      sloc: { logical: 26, physical: 44.25 },
    },
    module: "src\\connector.js",
  },
  jshint: { messages: [] },
};
