__report = {
  info: {
    file: "src\\gameTools.js",
    fileShort: "src\\gameTools.js",
    fileSafe: "src_gameTools_js",
    link: "files/src_gameTools_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 1,
      cyclomaticDensity: 5,
      halstead: {
        bugs: 0.497,
        difficulty: 15.969,
        effort: 23787.694,
        length: 237,
        time: 1321.539,
        vocabulary: 78,
        volume: 1489.64,
        operands: { distinct: 64, total: 146, identifiers: ["__stripped__"] },
        operators: { distinct: 14, total: 91, identifiers: ["__stripped__"] },
      },
      params: 1,
      sloc: { logical: 20, physical: 48 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./buildingTool", type: "esm" },
      { line: 11, path: "./bulldozerTool", type: "esm" },
      { line: 12, path: "./eventEmitter", type: "esm" },
      { line: 13, path: "./messages", type: "esm" },
      { line: 14, path: "./miscUtils", type: "esm" },
      { line: 15, path: "./parkTool", type: "esm" },
      { line: 16, path: "./railTool", type: "esm" },
      { line: 17, path: "./roadTool", type: "esm" },
      { line: 18, path: "./queryTool", type: "esm" },
      { line: 19, path: "./tileValues", type: "esm" },
      { line: 20, path: "./wireTool", type: "esm" },
    ],
    errors: [],
    lineEnd: 48,
    lineStart: 1,
    maintainability: 54.064,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 5.263,
        halstead: {
          bugs: 0.323,
          difficulty: 8.538,
          effort: 8271.464,
          length: 164,
          time: 459.526,
          vocabulary: 60,
          volume: 968.73,
          operands: { distinct: 52, total: 111, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 53, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 19, physical: 24 },
        errors: [],
        lineEnd: 45,
        lineStart: 22,
        name: "GameTools",
      },
    ],
    methodAverage: {
      cyclomatic: 1,
      cyclomaticDensity: 5.263,
      halstead: {
        bugs: 0.323,
        difficulty: 8.538,
        effort: 8271.464,
        length: 164,
        time: 459.526,
        vocabulary: 60,
        volume: 968.73,
        operands: { distinct: 52, total: 111 },
        operators: { distinct: 8, total: 53 },
      },
      params: 1,
      sloc: { logical: 19, physical: 24 },
    },
    module: "src\\gameTools.js",
  },
  jshint: { messages: [] },
};
