__report = {
  info: {
    file: "src\\stadia.js",
    fileShort: "src\\stadia.js",
    fileSafe: "src_stadia_js",
    link: "files/src_stadia_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 5,
      cyclomaticDensity: 25,
      halstead: {
        bugs: 0.354,
        difficulty: 25.368,
        effort: 26919.644,
        length: 189,
        time: 1495.536,
        vocabulary: 49,
        volume: 1061.18,
        operands: { distinct: 34, total: 115, identifiers: ["__stripped__"] },
        operators: { distinct: 15, total: 74, identifiers: ["__stripped__"] },
      },
      params: 10,
      sloc: { logical: 20, physical: 49 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./tileFlags", type: "esm" },
      { line: 11, path: "./tileValues", type: "esm" },
    ],
    errors: [],
    lineEnd: 49,
    lineStart: 1,
    maintainability: 69.307,
    methods: [
      {
        cyclomatic: 3,
        cyclomaticDensity: 42.857,
        halstead: {
          bugs: 0.112,
          difficulty: 7.5,
          effort: 2523.861,
          length: 70,
          time: 140.215,
          vocabulary: 28,
          volume: 336.515,
          operands: { distinct: 21, total: 45, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 25, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 7, physical: 13 },
        errors: [],
        lineEnd: 25,
        lineStart: 13,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.081,
          difficulty: 8.471,
          effort: 2070.405,
          length: 52,
          time: 115.023,
          vocabulary: 26,
          volume: 244.423,
          operands: { distinct: 17, total: 32, identifiers: ["__stripped__"] },
          operators: { distinct: 9, total: 20, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 6, physical: 10 },
        errors: [],
        lineEnd: 37,
        lineStart: 28,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.024,
          difficulty: 1.667,
          effort: 121.08,
          length: 21,
          time: 6.727,
          vocabulary: 11,
          volume: 72.648,
          operands: { distinct: 9, total: 15, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 6, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 3, physical: 5 },
        errors: [],
        lineEnd: 45,
        lineStart: 41,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 2.333,
      cyclomaticDensity: 42.063,
      halstead: {
        bugs: 0.073,
        difficulty: 5.879,
        effort: 1571.782,
        length: 47.667,
        time: 87.321,
        vocabulary: 21.667,
        volume: 217.862,
        operands: { distinct: 15.667, total: 30.667 },
        operators: { distinct: 6, total: 17 },
      },
      params: 3.333,
      sloc: { logical: 5.333, physical: 9.333 },
    },
    module: "src\\stadia.js",
  },
  jshint: { messages: [] },
};
