__report = {
  info: {
    file: "src\\splashCanvas.js",
    fileShort: "src\\splashCanvas.js",
    fileSafe: "src_splashCanvas_js",
    link: "files/src_splashCanvas_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 12,
      cyclomaticDensity: 25.532,
      halstead: {
        bugs: 0.681,
        difficulty: 36.066,
        effort: 73701.882,
        length: 318,
        time: 4094.549,
        vocabulary: 86,
        volume: 2043.552,
        operands: { distinct: 61, total: 176, identifiers: ["__stripped__"] },
        operators: { distinct: 25, total: 142, identifiers: ["__stripped__"] },
      },
      params: 8,
      sloc: { logical: 47, physical: 100 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [{ line: 10, path: "./miscUtils", type: "esm" }],
    errors: [],
    lineEnd: 100,
    lineStart: 1,
    maintainability: 57.045,
    methods: [
      {
        cyclomatic: 10,
        cyclomaticDensity: 31.25,
        halstead: {
          bugs: 0.362,
          difficulty: 19.317,
          effort: 20957.432,
          length: 186,
          time: 1164.302,
          vocabulary: 57,
          volume: 1084.918,
          operands: { distinct: 41, total: 99, identifiers: ["__stripped__"] },
          operators: { distinct: 16, total: 87, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 32, physical: 44 },
        errors: [],
        lineEnd: 72,
        lineStart: 29,
        name: "SplashCanvas",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.032,
          difficulty: 4.722,
          effort: 449.479,
          length: 25,
          time: 24.971,
          vocabulary: 14,
          volume: 95.184,
          operands: { distinct: 9, total: 17, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 8, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 79,
        lineStart: 76,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 42.857,
        halstead: {
          bugs: 0.094,
          difficulty: 9.25,
          effort: 2600.252,
          length: 64,
          time: 144.458,
          vocabulary: 21,
          volume: 281.108,
          operands: { distinct: 14, total: 37, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 27, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 7, physical: 10 },
        errors: [],
        lineEnd: 92,
        lineStart: 83,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 4.667,
      cyclomaticDensity: 41.369,
      halstead: {
        bugs: 0.162,
        difficulty: 11.096,
        effort: 8002.388,
        length: 91.667,
        time: 444.577,
        vocabulary: 30.667,
        volume: 487.07,
        operands: { distinct: 21.333, total: 51 },
        operators: { distinct: 9.333, total: 40.667 },
      },
      params: 2.667,
      sloc: { logical: 13.667, physical: 19.333 },
    },
    module: "src\\splashCanvas.js",
  },
  jshint: { messages: [] },
};
