__report = {
  info: {
    file: "src\\text.js",
    fileShort: "src\\text.js",
    fileSafe: "src_text_js",
    link: "files/src_text_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 1,
      cyclomaticDensity: 0.787,
      halstead: {
        bugs: 2.2,
        difficulty: 15.644,
        effort: 103247.981,
        length: 861,
        time: 5735.999,
        vocabulary: 203,
        volume: 6599.854,
        operands: { distinct: 191, total: 498, identifiers: ["__stripped__"] },
        operators: { distinct: 12, total: 363, identifiers: ["__stripped__"] },
      },
      params: 0,
      sloc: { logical: 127, physical: 167 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./evaluation", type: "esm" },
      { line: 11, path: "./messages", type: "esm" },
      { line: 12, path: "./simulation", type: "esm" },
    ],
    errors: [],
    lineEnd: 167,
    lineStart: 1,
    maintainability: 31.018,
    methods: [],
    methodAverage: {
      cyclomatic: 1,
      cyclomaticDensity: 0.787,
      halstead: {
        bugs: 2.2,
        difficulty: 15.644,
        effort: 103247.981,
        length: 861,
        time: 5735.999,
        vocabulary: 203,
        volume: 6599.854,
        operands: { distinct: 191, total: 498 },
        operators: { distinct: 12, total: 363 },
      },
      params: 0,
      sloc: { logical: 127, physical: 167 },
    },
    module: "src\\text.js",
  },
  jshint: { messages: [] },
};
