__report = {
  info: {
    file: "src\\bulldozerTool.js",
    fileShort: "src\\bulldozerTool.js",
    fileSafe: "src_bulldozerTool_js",
    link: "files/src_bulldozerTool_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 33,
      cyclomaticDensity: 37.079,
      halstead: {
        bugs: 1.323,
        difficulty: 50.622,
        effort: 200995.853,
        length: 570,
        time: 11166.436,
        vocabulary: 125,
        volume: 3970.497,
        operands: { distinct: 94, total: 307, identifiers: ["__stripped__"] },
        operators: { distinct: 31, total: 263, identifiers: ["__stripped__"] },
      },
      params: 9,
      sloc: { logical: 89, physical: 143 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./connectingTool", type: "esm" },
      { line: 11, path: "./eventEmitter", type: "esm" },
      { line: 12, path: "./messages", type: "esm" },
      { line: 13, path: "./random", type: "esm" },
      { line: 14, path: "./tileFlags", type: "esm" },
      { line: 15, path: "./tileUtils", type: "esm" },
      { line: 16, path: "./tileValues", type: "esm" },
      { line: 17, path: "./zoneUtils", type: "esm" },
    ],
    errors: [],
    lineEnd: 143,
    lineStart: 1,
    maintainability: 51.822,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.007,
          difficulty: 1.2,
          effort: 26.951,
          length: 8,
          time: 1.497,
          vocabulary: 7,
          volume: 22.459,
          operands: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 21,
        lineStart: 19,
        name: "<anonymous>",
      },
      {
        cyclomatic: 6,
        cyclomaticDensity: 75,
        halstead: {
          bugs: 0.133,
          difficulty: 12.571,
          effort: 5009.804,
          length: 79,
          time: 278.322,
          vocabulary: 33,
          volume: 398.507,
          operands: { distinct: 21, total: 44, identifiers: ["__stripped__"] },
          operators: { distinct: 12, total: 35, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 8, physical: 11 },
        errors: [],
        lineEnd: 34,
        lineStart: 24,
        name: "<anonymous>",
      },
      {
        cyclomatic: 18,
        cyclomaticDensity: 62.069,
        halstead: {
          bugs: 0.249,
          difficulty: 11.485,
          effort: 8578.275,
          length: 136,
          time: 476.571,
          vocabulary: 45,
          volume: 746.892,
          operands: { distinct: 34, total: 71, identifiers: ["__stripped__"] },
          operators: { distinct: 11, total: 65, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 29, physical: 38 },
        errors: [],
        lineEnd: 74,
        lineStart: 37,
        name: "<anonymous>",
      },
      {
        cyclomatic: 11,
        cyclomaticDensity: 23.404,
        halstead: {
          bugs: 0.504,
          difficulty: 25.067,
          effort: 37909.273,
          length: 255,
          time: 2106.071,
          vocabulary: 61,
          volume: 1512.338,
          operands: { distinct: 45, total: 141, identifiers: ["__stripped__"] },
          operators: {
            distinct: 16,
            total: 114,
            identifiers: ["__stripped__"],
          },
        },
        params: 3,
        sloc: { logical: 47, physical: 64 },
        errors: [],
        lineEnd: 140,
        lineStart: 77,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 9,
      cyclomaticDensity: 65.118,
      halstead: {
        bugs: 0.223,
        difficulty: 12.581,
        effort: 12881.076,
        length: 119.5,
        time: 715.615,
        vocabulary: 36.5,
        volume: 670.049,
        operands: { distinct: 26.25, total: 65.5 },
        operators: { distinct: 10.25, total: 54 },
      },
      params: 2.25,
      sloc: { logical: 21.25, physical: 29 },
    },
    module: "src\\bulldozerTool.js",
  },
  jshint: { messages: [] },
};
