__report = {
  info: {
    file: "src\\commercial.js",
    fileShort: "src\\commercial.js",
    fileSafe: "src_commercial_js",
    link: "files/src_commercial_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 15,
      cyclomaticDensity: 29.412,
      halstead: {
        bugs: 0.997,
        difficulty: 49.257,
        effort: 147254.895,
        length: 449,
        time: 8180.827,
        vocabulary: 101,
        volume: 2989.537,
        operands: { distinct: 74, total: 270, identifiers: ["__stripped__"] },
        operators: { distinct: 27, total: 179, identifiers: ["__stripped__"] },
      },
      params: 30,
      sloc: { logical: 51, physical: 148 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./random", type: "esm" },
      { line: 11, path: "./tileUtils", type: "esm" },
      { line: 12, path: "./tileValues", type: "esm" },
      { line: 13, path: "./traffic", type: "esm" },
      { line: 14, path: "./zoneUtils", type: "esm" },
    ],
    errors: [],
    lineEnd: 148,
    lineStart: 1,
    maintainability: 63.76,
    methods: [
      {
        cyclomatic: 2,
        cyclomaticDensity: 66.667,
        halstead: {
          bugs: 0.035,
          difficulty: 5.25,
          effort: 553.432,
          length: 24,
          time: 30.746,
          vocabulary: 21,
          volume: 105.416,
          operands: { distinct: 12, total: 14, identifiers: ["__stripped__"] },
          operators: { distinct: 9, total: 10, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 3, physical: 6 },
        errors: [],
        lineEnd: 27,
        lineStart: 22,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.038,
          difficulty: 4.75,
          effort: 534.793,
          length: 27,
          time: 29.711,
          vocabulary: 18,
          volume: 112.588,
          operands: { distinct: 12, total: 19, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 8, identifiers: ["__stripped__"] },
        },
        params: 6,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 35,
        lineStart: 32,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 42.857,
        halstead: {
          bugs: 0.073,
          difficulty: 9.9,
          effort: 2178.774,
          length: 48,
          time: 121.043,
          vocabulary: 24,
          volume: 220.078,
          operands: { distinct: 15, total: 33, identifiers: ["__stripped__"] },
          operators: { distinct: 9, total: 15, identifiers: ["__stripped__"] },
        },
        params: 7,
        sloc: { logical: 7, physical: 15 },
        errors: [],
        lineEnd: 52,
        lineStart: 38,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 40,
        halstead: {
          bugs: 0.059,
          difficulty: 7,
          effort: 1248.641,
          length: 40,
          time: 69.369,
          vocabulary: 22,
          volume: 178.377,
          operands: { distinct: 15, total: 30, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 10, identifiers: ["__stripped__"] },
        },
        params: 7,
        sloc: { logical: 5, physical: 11 },
        errors: [],
        lineEnd: 65,
        lineStart: 55,
        name: "<anonymous>",
      },
      {
        cyclomatic: 11,
        cyclomaticDensity: 44,
        halstead: {
          bugs: 0.449,
          difficulty: 23.644,
          effort: 31831.981,
          length: 227,
          time: 1768.443,
          vocabulary: 61,
          volume: 1346.277,
          operands: { distinct: 45, total: 133, identifiers: ["__stripped__"] },
          operators: { distinct: 16, total: 94, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 25, physical: 69 },
        errors: [],
        lineEnd: 137,
        lineStart: 69,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.01,
          difficulty: 1.167,
          effort: 35,
          length: 10,
          time: 1.944,
          vocabulary: 8,
          volume: 30,
          operands: { distinct: 6, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 3, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 143,
        lineStart: 141,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 3.333,
      cyclomaticDensity: 57.254,
      halstead: {
        bugs: 0.111,
        difficulty: 8.619,
        effort: 6063.77,
        length: 62.667,
        time: 336.876,
        vocabulary: 25.667,
        volume: 332.123,
        operands: { distinct: 17.5, total: 39.333 },
        operators: { distinct: 8.167, total: 23.333 },
      },
      params: 5,
      sloc: { logical: 7.167, physical: 18 },
    },
    module: "src\\commercial.js",
  },
  jshint: { messages: [] },
};
