__report = {
  info: {
    file: "src\\storage.js",
    fileShort: "src\\storage.js",
    fileSafe: "src_storage_js",
    link: "files/src_storage_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 5,
      cyclomaticDensity: 16.129,
      halstead: {
        bugs: 0.433,
        difficulty: 25.435,
        effort: 33053.638,
        length: 215,
        time: 1836.313,
        vocabulary: 66,
        volume: 1299.545,
        operands: { distinct: 46, total: 117, identifiers: ["__stripped__"] },
        operators: { distinct: 20, total: 98, identifiers: ["__stripped__"] },
      },
      params: 2,
      sloc: { logical: 31, physical: 72 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [{ line: 10, path: "./miscUtils", type: "esm" }],
    errors: [],
    lineEnd: 72,
    lineStart: 1,
    maintainability: 66.492,
    methods: [
      {
        cyclomatic: 3,
        cyclomaticDensity: 42.857,
        halstead: {
          bugs: 0.063,
          difficulty: 5.75,
          effort: 1086,
          length: 43,
          time: 60.333,
          vocabulary: 21,
          volume: 188.87,
          operands: { distinct: 14, total: 23, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 20, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 7, physical: 15 },
        errors: [],
        lineEnd: 29,
        lineStart: 15,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.031,
          difficulty: 2.25,
          effort: 208.15,
          length: 25,
          time: 11.564,
          vocabulary: 13,
          volume: 92.511,
          operands: { distinct: 10, total: 15, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 10, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 3, physical: 6 },
        errors: [],
        lineEnd: 37,
        lineStart: 32,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 27.273,
        halstead: {
          bugs: 0.113,
          difficulty: 11.875,
          effort: 4018.876,
          length: 72,
          time: 223.271,
          vocabulary: 26,
          volume: 338.432,
          operands: { distinct: 16, total: 38, identifiers: ["__stripped__"] },
          operators: { distinct: 10, total: 34, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 11, physical: 18 },
        errors: [],
        lineEnd: 57,
        lineStart: 40,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 2.333,
      cyclomaticDensity: 34.488,
      halstead: {
        bugs: 0.069,
        difficulty: 6.625,
        effort: 1771.009,
        length: 46.667,
        time: 98.389,
        vocabulary: 20,
        volume: 206.604,
        operands: { distinct: 13.333, total: 25.333 },
        operators: { distinct: 6.667, total: 21.333 },
      },
      params: 0.667,
      sloc: { logical: 7, physical: 13 },
    },
    module: "src\\storage.js",
  },
  jshint: { messages: [] },
};
