__report = {
  info: {
    file: "src\\transport.js",
    fileShort: "src\\transport.js",
    fileSafe: "src_transport_js",
    link: "files/src_transport_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 12,
      cyclomaticDensity: 30.769,
      halstead: {
        bugs: 0.778,
        difficulty: 31.908,
        effort: 74456.252,
        length: 356,
        time: 4136.458,
        vocabulary: 94,
        volume: 2333.434,
        operands: { distinct: 71, total: 197, identifiers: ["__stripped__"] },
        operators: { distinct: 23, total: 159, identifiers: ["__stripped__"] },
      },
      params: 14,
      sloc: { logical: 39, physical: 85 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./random", type: "esm" },
      { line: 11, path: "./spriteConstants", type: "esm" },
      { line: 12, path: "./tileFlags", type: "esm" },
      { line: 13, path: "./tileUtils", type: "esm" },
      { line: 14, path: "./tileValues", type: "esm" },
    ],
    errors: [],
    lineEnd: 85,
    lineStart: 1,
    maintainability: 63.128,
    methods: [
      {
        cyclomatic: 6,
        cyclomaticDensity: 46.154,
        halstead: {
          bugs: 0.178,
          difficulty: 9.581,
          effort: 5114.526,
          length: 99,
          time: 284.14,
          vocabulary: 42,
          volume: 533.839,
          operands: { distinct: 31, total: 54, identifiers: ["__stripped__"] },
          operators: { distinct: 11, total: 45, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 13, physical: 24 },
        errors: [],
        lineEnd: 39,
        lineStart: 16,
        name: "<anonymous>",
      },
      {
        cyclomatic: 5,
        cyclomaticDensity: 41.667,
        halstead: {
          bugs: 0.189,
          difficulty: 14.308,
          effort: 8109.259,
          length: 108,
          time: 450.514,
          vocabulary: 38,
          volume: 566.776,
          operands: { distinct: 26, total: 62, identifiers: ["__stripped__"] },
          operators: { distinct: 12, total: 46, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 12, physical: 19 },
        errors: [],
        lineEnd: 60,
        lineStart: 42,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 75,
        halstead: {
          bugs: 0.062,
          difficulty: 6.133,
          effort: 1137.525,
          length: 41,
          time: 63.196,
          vocabulary: 23,
          volume: 185.466,
          operands: { distinct: 15, total: 23, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 18, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 4, physical: 8 },
        errors: [],
        lineEnd: 70,
        lineStart: 63,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 20,
        halstead: {
          bugs: 0.06,
          difficulty: 1.933,
          effort: 347.707,
          length: 44,
          time: 19.317,
          vocabulary: 17,
          volume: 179.848,
          operands: { distinct: 15, total: 29, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 15, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 5, physical: 8 },
        errors: [],
        lineEnd: 81,
        lineStart: 74,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 3.75,
      cyclomaticDensity: 45.705,
      halstead: {
        bugs: 0.122,
        difficulty: 7.989,
        effort: 3677.254,
        length: 73,
        time: 204.292,
        vocabulary: 30,
        volume: 366.483,
        operands: { distinct: 21.75, total: 42 },
        operators: { distinct: 8.25, total: 31 },
      },
      params: 3.5,
      sloc: { logical: 8.5, physical: 14.75 },
    },
    module: "src\\transport.js",
  },
  jshint: { messages: [] },
};
