__report = {
  info: {
    file: "src\\miscTiles.js",
    fileShort: "src\\miscTiles.js",
    fileSafe: "src_miscTiles_js",
    link: "files/src_miscTiles_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 13,
      cyclomaticDensity: 30.952,
      halstead: {
        bugs: 0.665,
        difficulty: 33.682,
        effort: 67235.981,
        length: 306,
        time: 3735.332,
        vocabulary: 92,
        volume: 1996.21,
        operands: { distinct: 66, total: 171, identifiers: ["__stripped__"] },
        operators: { distinct: 26, total: 135, identifiers: ["__stripped__"] },
      },
      params: 14,
      sloc: { logical: 42, physical: 86 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./random", type: "esm" },
      { line: 11, path: "./tileUtils", type: "esm" },
      { line: 12, path: "./tileValues", type: "esm" },
      { line: 13, path: "./zoneUtils", type: "esm" },
    ],
    errors: [],
    lineEnd: 86,
    lineStart: 1,
    maintainability: 62.298,
    methods: [
      {
        cyclomatic: 12,
        cyclomaticDensity: 41.379,
        halstead: {
          bugs: 0.339,
          difficulty: 18.614,
          effort: 18951.801,
          length: 171,
          time: 1052.878,
          vocabulary: 62,
          volume: 1018.168,
          operands: { distinct: 44, total: 91, identifiers: ["__stripped__"] },
          operators: { distinct: 18, total: 80, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 29, physical: 46 },
        errors: [],
        lineEnd: 63,
        lineStart: 18,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.022,
          difficulty: 1.95,
          effort: 129.885,
          length: 18,
          time: 7.216,
          vocabulary: 13,
          volume: 66.608,
          operands: { distinct: 10, total: 13, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 5, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 69,
        lineStart: 66,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.016,
          difficulty: 1.571,
          effort: 74.72,
          length: 15,
          time: 4.151,
          vocabulary: 9,
          volume: 47.549,
          operands: { distinct: 7, total: 11, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 4, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 74,
        lineStart: 72,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.033,
          difficulty: 1.727,
          effort: 172.575,
          length: 27,
          time: 9.588,
          vocabulary: 13,
          volume: 99.912,
          operands: { distinct: 11, total: 19, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 8, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 3, physical: 5 },
        errors: [],
        lineEnd: 82,
        lineStart: 78,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 4,
      cyclomaticDensity: 68.678,
      halstead: {
        bugs: 0.103,
        difficulty: 5.966,
        effort: 4832.245,
        length: 57.75,
        time: 268.458,
        vocabulary: 24.25,
        volume: 308.059,
        operands: { distinct: 18, total: 33.5 },
        operators: { distinct: 6.25, total: 24.25 },
      },
      params: 3.5,
      sloc: { logical: 8.75, physical: 14.5 },
    },
    module: "src\\miscTiles.js",
  },
  jshint: { messages: [] },
};
