__report = {
  info: {
    file: "src\\saveWindow.js",
    fileShort: "src\\saveWindow.js",
    fileSafe: "src_saveWindow_js",
    link: "files/src_saveWindow_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 1,
      cyclomaticDensity: 7.692,
      halstead: {
        bugs: 0.155,
        difficulty: 8.813,
        effort: 4089.743,
        length: 92,
        time: 227.208,
        vocabulary: 33,
        volume: 464.084,
        operands: { distinct: 24, total: 47, identifiers: ["__stripped__"] },
        operators: { distinct: 9, total: 45, identifiers: ["__stripped__"] },
      },
      params: 1,
      sloc: { logical: 13, physical: 40 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./messages", type: "esm" },
      { line: 11, path: "./modalWindow", type: "esm" },
    ],
    errors: [],
    lineEnd: 40,
    lineStart: 1,
    maintainability: 87.826,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.013,
          difficulty: 1,
          effort: 38.039,
          length: 12,
          time: 2.113,
          vocabulary: 9,
          volume: 38.039,
          operands: { distinct: 7, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 5, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 15,
        lineStart: 13,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.008,
          difficulty: 1.25,
          effort: 29.081,
          length: 9,
          time: 1.616,
          vocabulary: 6,
          volume: 23.265,
          operands: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 4, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 25,
        lineStart: 22,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.008,
          difficulty: 1.25,
          effort: 29.081,
          length: 9,
          time: 1.616,
          vocabulary: 6,
          volume: 23.265,
          operands: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 4, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 31,
        lineStart: 28,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.009,
          difficulty: 1,
          effort: 28.074,
          length: 10,
          time: 1.56,
          vocabulary: 7,
          volume: 28.074,
          operands: { distinct: 5, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 5, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 37,
        lineStart: 34,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 1,
      cyclomaticDensity: 62.5,
      halstead: {
        bugs: 0.009,
        difficulty: 1.125,
        effort: 31.069,
        length: 10,
        time: 1.726,
        vocabulary: 7,
        volume: 28.16,
        operands: { distinct: 5, total: 5.5 },
        operators: { distinct: 2, total: 4.5 },
      },
      params: 0.25,
      sloc: { logical: 1.75, physical: 3.75 },
    },
    module: "src\\saveWindow.js",
  },
  jshint: { messages: [] },
};
