__report = {
  info: {
    file: "src\\airplaneSprite.js",
    fileShort: "src\\airplaneSprite.js",
    fileSafe: "src_airplaneSprite_js",
    link: "files/src_airplaneSprite_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 15,
      cyclomaticDensity: 25,
      halstead: {
        bugs: 1.068,
        difficulty: 46.212,
        effort: 148001.468,
        length: 477,
        time: 8222.304,
        vocabulary: 105,
        volume: 3202.695,
        operands: { distinct: 78, total: 267, identifiers: ["__stripped__"] },
        operators: { distinct: 27, total: 210, identifiers: ["__stripped__"] },
      },
      params: 7,
      sloc: { logical: 60, physical: 110 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./baseSprite", type: "esm" },
      { line: 11, path: "./messages", type: "esm" },
      { line: 12, path: "./miscUtils", type: "esm" },
      { line: 13, path: "./random", type: "esm" },
      { line: 14, path: "./spriteConstants", type: "esm" },
      { line: 15, path: "./spriteUtils", type: "esm" },
    ],
    errors: [],
    lineEnd: 110,
    lineStart: 1,
    maintainability: 54.199,
    methods: [
      {
        cyclomatic: 2,
        cyclomaticDensity: 16.667,
        halstead: {
          bugs: 0.137,
          difficulty: 10.023,
          effort: 4121.328,
          length: 83,
          time: 228.963,
          vocabulary: 31,
          volume: 411.198,
          operands: { distinct: 22, total: 49, identifiers: ["__stripped__"] },
          operators: { distinct: 9, total: 34, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 12, physical: 15 },
        errors: [],
        lineEnd: 31,
        lineStart: 17,
        name: "AirplaneSprite",
      },
      {
        cyclomatic: 14,
        cyclomaticDensity: 43.75,
        halstead: {
          bugs: 0.456,
          difficulty: 24.6,
          effort: 33672.409,
          length: 229,
          time: 1870.689,
          vocabulary: 63,
          volume: 1368.797,
          operands: { distinct: 45, total: 123, identifiers: ["__stripped__"] },
          operators: {
            distinct: 18,
            total: 106,
            identifiers: ["__stripped__"],
          },
        },
        params: 3,
        sloc: { logical: 32, physical: 54 },
        errors: [],
        lineEnd: 93,
        lineStart: 40,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 16.667,
        halstead: {
          bugs: 0.05,
          difficulty: 4.038,
          effort: 606.243,
          length: 36,
          time: 33.68,
          vocabulary: 18,
          volume: 150.117,
          operands: { distinct: 13, total: 21, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 15, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 6, physical: 5 },
        errors: [],
        lineEnd: 100,
        lineStart: 96,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 5.667,
      cyclomaticDensity: 25.694,
      halstead: {
        bugs: 0.214,
        difficulty: 12.887,
        effort: 12799.993,
        length: 116,
        time: 711.111,
        vocabulary: 37.333,
        volume: 643.371,
        operands: { distinct: 26.667, total: 64.333 },
        operators: { distinct: 10.667, total: 51.667 },
      },
      params: 2.333,
      sloc: { logical: 16.667, physical: 24.667 },
    },
    module: "src\\airplaneSprite.js",
  },
  jshint: { messages: [] },
};
