__report = {
  info: {
    file: "src\\residential.js",
    fileShort: "src\\residential.js",
    fileSafe: "src_residential_js",
    link: "files/src_residential_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 57,
      cyclomaticDensity: 36.076,
      halstead: {
        bugs: 3.165,
        difficulty: 103.572,
        effort: 983449.857,
        length: 1283,
        time: 54636.103,
        vocabulary: 169,
        volume: 9495.328,
        operands: { distinct: 132, total: 739, identifiers: ["__stripped__"] },
        operators: { distinct: 37, total: 544, identifiers: ["__stripped__"] },
      },
      params: 54,
      sloc: { logical: 158, physical: 319 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./config", type: "esm" },
      { line: 11, path: "./random", type: "esm" },
      { line: 12, path: "./tile", type: "esm" },
      { line: 13, path: "./tileFlags", type: "esm" },
      { line: 14, path: "./tileUtils", type: "esm" },
      { line: 15, path: "./tileValues", type: "esm" },
      { line: 16, path: "./traffic", type: "esm" },
      { line: 17, path: "./zoneUtils", type: "esm" },
    ],
    errors: [],
    lineEnd: 319,
    lineStart: 1,
    maintainability: 57.522,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.041,
          difficulty: 4.615,
          effort: 568.569,
          length: 29,
          time: 31.587,
          vocabulary: 19,
          volume: 123.19,
          operands: { distinct: 13, total: 20, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 9, identifiers: ["__stripped__"] },
        },
        params: 6,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 24,
        lineStart: 21,
        name: "<anonymous>",
      },
      {
        cyclomatic: 7,
        cyclomaticDensity: 63.636,
        halstead: {
          bugs: 0.113,
          difficulty: 23.385,
          effort: 7952.141,
          length: 70,
          time: 441.786,
          vocabulary: 29,
          volume: 340.059,
          operands: { distinct: 13, total: 38, identifiers: ["__stripped__"] },
          operators: { distinct: 16, total: 32, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 11, physical: 13 },
        errors: [],
        lineEnd: 40,
        lineStart: 28,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.085,
          difficulty: 9.921,
          effort: 2529.868,
          length: 51,
          time: 140.548,
          vocabulary: 32,
          volume: 255,
          operands: { distinct: 19, total: 29, identifiers: ["__stripped__"] },
          operators: { distinct: 13, total: 22, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 6, physical: 10 },
        errors: [],
        lineEnd: 52,
        lineStart: 43,
        name: "<anonymous>",
      },
      {
        cyclomatic: 11,
        cyclomaticDensity: 61.111,
        halstead: {
          bugs: 0.242,
          difficulty: 33.409,
          effort: 24292.401,
          length: 134,
          time: 1349.578,
          vocabulary: 43,
          volume: 727.119,
          operands: { distinct: 22, total: 70, identifiers: ["__stripped__"] },
          operators: { distinct: 21, total: 64, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 18, physical: 26 },
        errors: [],
        lineEnd: 81,
        lineStart: 56,
        name: "<anonymous>",
      },
      {
        cyclomatic: 7,
        cyclomaticDensity: 41.176,
        halstead: {
          bugs: 0.27,
          difficulty: 25.185,
          effort: 20362.561,
          length: 149,
          time: 1131.253,
          vocabulary: 43,
          volume: 808.513,
          operands: { distinct: 27, total: 85, identifiers: ["__stripped__"] },
          operators: { distinct: 16, total: 64, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 17, physical: 27 },
        errors: [],
        lineEnd: 110,
        lineStart: 84,
        name: "<anonymous>",
      },
      {
        cyclomatic: 6,
        cyclomaticDensity: 37.5,
        halstead: {
          bugs: 0.199,
          difficulty: 16.444,
          effort: 9821.452,
          length: 113,
          time: 545.636,
          vocabulary: 39,
          volume: 597.25,
          operands: { distinct: 27, total: 74, identifiers: ["__stripped__"] },
          operators: { distinct: 12, total: 39, identifiers: ["__stripped__"] },
        },
        params: 7,
        sloc: { logical: 16, physical: 29 },
        errors: [],
        lineEnd: 141,
        lineStart: 113,
        name: "<anonymous>",
      },
      {
        cyclomatic: 12,
        cyclomaticDensity: 48,
        halstead: {
          bugs: 0.384,
          difficulty: 32.971,
          effort: 37959.434,
          length: 201,
          time: 2108.857,
          vocabulary: 53,
          volume: 1151.312,
          operands: { distinct: 34, total: 118, identifiers: ["__stripped__"] },
          operators: { distinct: 19, total: 83, identifiers: ["__stripped__"] },
        },
        params: 7,
        sloc: { logical: 25, physical: 42 },
        errors: [],
        lineEnd: 187,
        lineStart: 146,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.091,
          difficulty: 13,
          effort: 3536.61,
          length: 56,
          time: 196.478,
          vocabulary: 29,
          volume: 272.047,
          operands: { distinct: 16, total: 32, identifiers: ["__stripped__"] },
          operators: { distinct: 13, total: 24, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 9, physical: 14 },
        errors: [],
        lineEnd: 204,
        lineStart: 191,
        name: "<anonymous>",
      },
      {
        cyclomatic: 12,
        cyclomaticDensity: 42.857,
        halstead: {
          bugs: 0.478,
          difficulty: 23.667,
          effort: 33938,
          length: 239,
          time: 1885.444,
          vocabulary: 64,
          volume: 1434,
          operands: { distinct: 48, total: 142, identifiers: ["__stripped__"] },
          operators: { distinct: 16, total: 97, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 28, physical: 79 },
        errors: [],
        lineEnd: 285,
        lineStart: 207,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.044,
          difficulty: 5.25,
          effort: 700.547,
          length: 32,
          time: 38.919,
          vocabulary: 18,
          volume: 133.438,
          operands: { distinct: 12, total: 21, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 11, identifiers: ["__stripped__"] },
        },
        params: 5,
        sloc: { logical: 4, physical: 8 },
        errors: [],
        lineEnd: 295,
        lineStart: 288,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 75,
        halstead: {
          bugs: 0.072,
          difficulty: 4.667,
          effort: 1005.635,
          length: 47,
          time: 55.869,
          vocabulary: 24,
          volume: 215.493,
          operands: { distinct: 18, total: 28, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 19, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 4, physical: 9 },
        errors: [],
        lineEnd: 306,
        lineStart: 298,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.033,
          difficulty: 1.636,
          effort: 163.492,
          length: 27,
          time: 9.083,
          vocabulary: 13,
          volume: 99.912,
          operands: { distinct: 11, total: 18, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 9, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 3, physical: 5 },
        errors: [],
        lineEnd: 314,
        lineStart: 310,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 5.667,
      cyclomaticDensity: 48.829,
      halstead: {
        bugs: 0.171,
        difficulty: 16.179,
        effort: 11902.559,
        length: 95.667,
        time: 661.253,
        vocabulary: 33.833,
        volume: 513.111,
        operands: { distinct: 21.667, total: 56.25 },
        operators: { distinct: 12.167, total: 39.417 },
      },
      params: 4.5,
      sloc: { logical: 11.917, physical: 22.167 },
    },
    module: "src\\residential.js",
  },
  jshint: { messages: [] },
};
