__report = {
  info: {
    file: "src\\valves.js",
    fileShort: "src\\valves.js",
    fileSafe: "src_valves_js",
    link: "files/src_valves_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 12,
      cyclomaticDensity: 13.953,
      halstead: {
        bugs: 1.427,
        difficulty: 32.959,
        effort: 141073.125,
        length: 623,
        time: 7837.396,
        vocabulary: 117,
        volume: 4280.237,
        operands: { distinct: 98, total: 340, identifiers: ["__stripped__"] },
        operators: { distinct: 19, total: 283, identifiers: ["__stripped__"] },
      },
      params: 5,
      sloc: { logical: 86, physical: 142 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./eventEmitter", type: "esm" },
      { line: 11, path: "./messages", type: "esm" },
      { line: 12, path: "./miscUtils", type: "esm" },
    ],
    errors: [],
    lineEnd: 142,
    lineStart: 1,
    maintainability: 52.419,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 16.667,
        halstead: {
          bugs: 0.035,
          difficulty: 2,
          effort: 207.566,
          length: 30,
          time: 11.531,
          vocabulary: 11,
          volume: 103.783,
          operands: { distinct: 9, total: 18, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 12, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 6, physical: 8 },
        errors: [],
        lineEnd: 21,
        lineStart: 14,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.021,
          difficulty: 2.6,
          effort: 160.581,
          length: 22,
          time: 8.921,
          vocabulary: 7,
          volume: 61.762,
          operands: { distinct: 5, total: 13, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 9, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 3, physical: 5 },
        errors: [],
        lineEnd: 38,
        lineStart: 34,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.03,
          difficulty: 3.429,
          effort: 307.516,
          length: 27,
          time: 17.084,
          vocabulary: 10,
          volume: 89.692,
          operands: { distinct: 7, total: 16, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 11, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 7 },
        errors: [],
        lineEnd: 47,
        lineStart: 41,
        name: "<anonymous>",
      },
      {
        cyclomatic: 12,
        cyclomaticDensity: 18.75,
        halstead: {
          bugs: 0.909,
          difficulty: 23.5,
          effort: 64104.817,
          length: 434,
          time: 3561.379,
          vocabulary: 78,
          volume: 2727.865,
          operands: { distinct: 65, total: 235, identifiers: ["__stripped__"] },
          operators: {
            distinct: 13,
            total: 199,
            identifiers: ["__stripped__"],
          },
        },
        params: 3,
        sloc: { logical: 64, physical: 90 },
        errors: [],
        lineEnd: 139,
        lineStart: 50,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 3.75,
      cyclomaticDensity: 23.438,
      halstead: {
        bugs: 0.249,
        difficulty: 7.882,
        effort: 16195.12,
        length: 128.25,
        time: 899.729,
        vocabulary: 26.5,
        volume: 745.775,
        operands: { distinct: 21.5, total: 70.5 },
        operators: { distinct: 5, total: 57.75 },
      },
      params: 1.25,
      sloc: { logical: 19.25, physical: 27.5 },
    },
    module: "src\\valves.js",
  },
  jshint: { messages: [] },
};
