__report = {
  info: {
    file: "src\\tileHistory.js",
    fileShort: "src\\tileHistory.js",
    fileSafe: "src_tileHistory_js",
    link: "files/src_tileHistory_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 1,
      cyclomaticDensity: 7.692,
      halstead: {
        bugs: 0.131,
        difficulty: 14.1,
        effort: 5559.726,
        length: 86,
        time: 308.874,
        vocabulary: 24,
        volume: 394.307,
        operands: { distinct: 15, total: 47, identifiers: ["__stripped__"] },
        operators: { distinct: 9, total: 39, identifiers: ["__stripped__"] },
      },
      params: 7,
      sloc: { logical: 13, physical: 37 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [],
    errors: [],
    lineEnd: 37,
    lineStart: 1,
    maintainability: 86.358,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.003,
          difficulty: 1,
          effort: 8,
          length: 4,
          time: 0.444,
          vocabulary: 4,
          volume: 8,
          operands: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 12,
        lineStart: 10,
        name: "TileHistory",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.01,
          difficulty: 3,
          effort: 90,
          length: 10,
          time: 5,
          vocabulary: 8,
          volume: 30,
          operands: { distinct: 4, total: 6, identifiers: ["__stripped__"] },
          operators: { distinct: 4, total: 4, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 2, physical: 3 },
        errors: [],
        lineEnd: 17,
        lineStart: 15,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.004,
          difficulty: 1.5,
          effort: 17.414,
          length: 5,
          time: 0.967,
          vocabulary: 5,
          volume: 11.61,
          operands: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 3, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 22,
        lineStart: 20,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.017,
          difficulty: 3.75,
          effort: 194.593,
          length: 15,
          time: 10.811,
          vocabulary: 11,
          volume: 51.891,
          operands: { distinct: 6, total: 9, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 6, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 28,
        lineStart: 25,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.02,
          difficulty: 3.143,
          effort: 184.832,
          length: 17,
          time: 10.268,
          vocabulary: 11,
          volume: 58.81,
          operands: { distinct: 7, total: 11, identifiers: ["__stripped__"] },
          operators: { distinct: 4, total: 6, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 34,
        lineStart: 31,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 1,
      cyclomaticDensity: 70,
      halstead: {
        bugs: 0.011,
        difficulty: 2.479,
        effort: 98.968,
        length: 10.2,
        time: 5.498,
        vocabulary: 7.8,
        volume: 32.062,
        operands: { distinct: 4.2, total: 6 },
        operators: { distinct: 3.6, total: 4.2 },
      },
      params: 1.4,
      sloc: { logical: 1.6, physical: 3.4 },
    },
    module: "src\\tileHistory.js",
  },
  jshint: { messages: [] },
};
