__report = {
  info: {
    file: "src\\notification.js",
    fileShort: "src\\notification.js",
    fileSafe: "src_notification_js",
    link: "files/src_notification_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 14,
      cyclomaticDensity: 19.718,
      halstead: {
        bugs: 1.114,
        difficulty: 42.492,
        effort: 141965.276,
        length: 530,
        time: 7886.96,
        vocabulary: 79,
        volume: 3341.004,
        operands: { distinct: 61, total: 288, identifiers: ["__stripped__"] },
        operators: { distinct: 18, total: 242, identifiers: ["__stripped__"] },
      },
      params: 15,
      sloc: { logical: 71, physical: 128 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./miscUtils", type: "esm" },
      { line: 11, path: "./text", type: "esm" },
    ],
    errors: [],
    lineEnd: 128,
    lineStart: 1,
    maintainability: 69.697,
    methods: [
      {
        cyclomatic: 2,
        cyclomaticDensity: 18.182,
        halstead: {
          bugs: 0.127,
          difficulty: 5.114,
          effort: 1945.181,
          length: 80,
          time: 108.066,
          vocabulary: 27,
          volume: 380.391,
          operands: { distinct: 22, total: 45, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 35, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 11, physical: 18 },
        errors: [],
        lineEnd: 33,
        lineStart: 16,
        name: "Notification",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 75,
        halstead: {
          bugs: 0.023,
          difficulty: 2.357,
          effort: 164.435,
          length: 21,
          time: 9.135,
          vocabulary: 10,
          volume: 69.76,
          operands: { distinct: 7, total: 11, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 10, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 7 },
        errors: [],
        lineEnd: 42,
        lineStart: 36,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 27.273,
        halstead: {
          bugs: 0.125,
          difficulty: 8.19,
          effort: 3063.767,
          length: 77,
          time: 170.209,
          vocabulary: 29,
          volume: 374.065,
          operands: { distinct: 21, total: 43, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 34, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 11, physical: 18 },
        errors: [],
        lineEnd: 62,
        lineStart: 45,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.008,
          difficulty: 1.875,
          effort: 47.374,
          length: 9,
          time: 2.632,
          vocabulary: 7,
          volume: 25.266,
          operands: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 4, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 1 },
        errors: [],
        lineEnd: 61,
        lineStart: 61,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 27.273,
        halstead: {
          bugs: 0.13,
          difficulty: 8.795,
          effort: 3442.378,
          length: 79,
          time: 191.243,
          vocabulary: 31,
          volume: 391.382,
          operands: { distinct: 22, total: 43, identifiers: ["__stripped__"] },
          operators: { distinct: 9, total: 36, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 11, physical: 16 },
        errors: [],
        lineEnd: 80,
        lineStart: 65,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.008,
          difficulty: 1.875,
          effort: 47.374,
          length: 9,
          time: 2.632,
          vocabulary: 7,
          volume: 25.266,
          operands: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 4, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 1 },
        errors: [],
        lineEnd: 79,
        lineStart: 79,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 75,
        halstead: {
          bugs: 0.042,
          difficulty: 7,
          effort: 875.143,
          length: 32,
          time: 48.619,
          vocabulary: 15,
          volume: 125.02,
          operands: { distinct: 8, total: 16, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 16, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 8 },
        errors: [],
        lineEnd: 90,
        lineStart: 83,
        name: "<anonymous>",
      },
      {
        cyclomatic: 5,
        cyclomaticDensity: 125,
        halstead: {
          bugs: 0.091,
          difficulty: 6.6,
          effort: 1797.336,
          length: 62,
          time: 99.852,
          vocabulary: 21,
          volume: 272.324,
          operands: { distinct: 15, total: 33, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 29, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 9 },
        errors: [],
        lineEnd: 101,
        lineStart: 93,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.031,
          difficulty: 1.778,
          effort: 166.053,
          length: 27,
          time: 9.225,
          vocabulary: 11,
          volume: 93.405,
          operands: { distinct: 9, total: 16, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 11, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 6 },
        errors: [],
        lineEnd: 109,
        lineStart: 104,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.031,
          difficulty: 1.778,
          effort: 166.053,
          length: 27,
          time: 9.225,
          vocabulary: 11,
          volume: 93.405,
          operands: { distinct: 9, total: 16, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 11, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 6 },
        errors: [],
        lineEnd: 117,
        lineStart: 112,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.031,
          difficulty: 1.778,
          effort: 166.053,
          length: 27,
          time: 9.225,
          vocabulary: 11,
          volume: 93.405,
          operands: { distinct: 9, total: 16, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 11, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 6 },
        errors: [],
        lineEnd: 125,
        lineStart: 120,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 2.182,
      cyclomaticDensity: 47.521,
      halstead: {
        bugs: 0.059,
        difficulty: 4.285,
        effort: 1080.104,
        length: 40.909,
        time: 60.006,
        vocabulary: 16.364,
        volume: 176.699,
        operands: { distinct: 11.818, total: 22.636 },
        operators: { distinct: 4.545, total: 18.273 },
      },
      params: 1.364,
      sloc: { logical: 5.545, physical: 8.727 },
    },
    module: "src\\notification.js",
  },
  jshint: { messages: [] },
};
