__report = {
  info: {
    file: "src\\wireTool.js",
    fileShort: "src\\wireTool.js",
    fileSafe: "src_wireTool_js",
    link: "files/src_wireTool_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 29,
      cyclomaticDensity: 43.284,
      halstead: {
        bugs: 1.146,
        difficulty: 59,
        effort: 202904.94,
        length: 538,
        time: 11272.497,
        vocabulary: 84,
        volume: 3439.067,
        operands: { distinct: 60, total: 295, identifiers: ["__stripped__"] },
        operators: { distinct: 24, total: 243, identifiers: ["__stripped__"] },
      },
      params: 6,
      sloc: { logical: 67, physical: 118 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./connectingTool", type: "esm" },
      { line: 11, path: "./tileFlags", type: "esm" },
      { line: 12, path: "./tileUtils", type: "esm" },
      { line: 13, path: "./tileValues", type: "esm" },
    ],
    errors: [],
    lineEnd: 118,
    lineStart: 1,
    maintainability: 49.312,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.008,
          difficulty: 1.4,
          effort: 35.373,
          length: 9,
          time: 1.965,
          vocabulary: 7,
          volume: 25.266,
          operands: { distinct: 5, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 17,
        lineStart: 15,
        name: "<anonymous>",
      },
      {
        cyclomatic: 29,
        cyclomaticDensity: 46.774,
        halstead: {
          bugs: 0.905,
          difficulty: 48.489,
          effort: 131708.602,
          length: 458,
          time: 7317.145,
          vocabulary: 61,
          volume: 2716.278,
          operands: { distinct: 44, total: 251, identifiers: ["__stripped__"] },
          operators: {
            distinct: 17,
            total: 207,
            identifiers: ["__stripped__"],
          },
        },
        params: 2,
        sloc: { logical: 62, physical: 91 },
        errors: [],
        lineEnd: 110,
        lineStart: 20,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.014,
          difficulty: 2.25,
          effort: 92.72,
          length: 13,
          time: 5.151,
          vocabulary: 9,
          volume: 41.209,
          operands: { distinct: 6, total: 9, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 4, identifiers: ["__stripped__"] },
        },
        params: 3,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 115,
        lineStart: 113,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 10.333,
      cyclomaticDensity: 82.258,
      halstead: {
        bugs: 0.309,
        difficulty: 17.38,
        effort: 43945.565,
        length: 160,
        time: 2441.42,
        vocabulary: 25.667,
        volume: 927.584,
        operands: { distinct: 18.333, total: 89 },
        operators: { distinct: 7.333, total: 71 },
      },
      params: 2,
      sloc: { logical: 21.333, physical: 32.333 },
    },
    module: "src\\wireTool.js",
  },
  jshint: { messages: [] },
};
