__report = {
  info: {
    file: "src\\congratsWindow.js",
    fileShort: "src\\congratsWindow.js",
    fileSafe: "src_congratsWindow_js",
    link: "files/src_congratsWindow_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 1,
      cyclomaticDensity: 6.667,
      halstead: {
        bugs: 0.181,
        difficulty: 8.679,
        effort: 4701.904,
        length: 104,
        time: 261.217,
        vocabulary: 37,
        volume: 541.783,
        operands: { distinct: 28, total: 54, identifiers: ["__stripped__"] },
        operators: { distinct: 9, total: 50, identifiers: ["__stripped__"] },
      },
      params: 2,
      sloc: { logical: 15, physical: 42 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./messages", type: "esm" },
      { line: 11, path: "./modalWindow", type: "esm" },
    ],
    errors: [],
    lineEnd: 42,
    lineStart: 1,
    maintainability: 85.923,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.013,
          difficulty: 1,
          effort: 38.039,
          length: 12,
          time: 2.113,
          vocabulary: 9,
          volume: 38.039,
          operands: { distinct: 7, total: 7, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 5, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 15,
        lineStart: 13,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.008,
          difficulty: 1.25,
          effort: 29.081,
          length: 9,
          time: 1.616,
          vocabulary: 6,
          volume: 23.265,
          operands: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 4, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 26,
        lineStart: 23,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.008,
          difficulty: 1.25,
          effort: 29.081,
          length: 9,
          time: 1.616,
          vocabulary: 6,
          volume: 23.265,
          operands: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 4, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 32,
        lineStart: 29,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.02,
          difficulty: 1.25,
          effort: 74.743,
          length: 18,
          time: 4.152,
          vocabulary: 10,
          volume: 59.795,
          operands: { distinct: 8, total: 10, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 8, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 3, physical: 5 },
        errors: [],
        lineEnd: 39,
        lineStart: 35,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 1,
      cyclomaticDensity: 58.333,
      halstead: {
        bugs: 0.012,
        difficulty: 1.188,
        effort: 42.736,
        length: 12,
        time: 2.374,
        vocabulary: 7.75,
        volume: 36.091,
        operands: { distinct: 5.75, total: 6.75 },
        operators: { distinct: 2, total: 5.25 },
      },
      params: 0.5,
      sloc: { logical: 2, physical: 4 },
    },
    module: "src\\congratsWindow.js",
  },
  jshint: { messages: [] },
};
