__report = {
  info: {
    file: "src\\powerManager.js",
    fileShort: "src\\powerManager.js",
    fileSafe: "src_powerManager_js",
    link: "files/src_powerManager_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 18,
      cyclomaticDensity: 24.324,
      halstead: {
        bugs: 1.407,
        difficulty: 49.778,
        effort: 210127.079,
        length: 605,
        time: 11673.727,
        vocabulary: 126,
        volume: 4221.254,
        operands: { distinct: 97, total: 333, identifiers: ["__stripped__"] },
        operators: { distinct: 29, total: 272, identifiers: ["__stripped__"] },
      },
      params: 17,
      sloc: { logical: 74, physical: 156 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./blockMap", type: "esm" },
      { line: 11, path: "./direction", type: "esm" },
      { line: 12, path: "./eventEmitter", type: "esm" },
      { line: 13, path: "./position", type: "esm" },
      { line: 14, path: "./messages", type: "esm" },
      { line: 15, path: "./random", type: "esm" },
      { line: 16, path: "./tileFlags", type: "esm" },
      { line: 17, path: "./tileValues", type: "esm" },
    ],
    errors: [],
    lineEnd: 156,
    lineStart: 1,
    maintainability: 66.226,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 33.333,
        halstead: {
          bugs: 0.035,
          difficulty: 3.556,
          effort: 368.399,
          length: 28,
          time: 20.467,
          vocabulary: 13,
          volume: 103.612,
          operands: { distinct: 9, total: 16, identifiers: ["__stripped__"] },
          operators: { distinct: 4, total: 12, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 3, physical: 5 },
        errors: [],
        lineEnd: 27,
        lineStart: 23,
        name: "<anonymous>",
      },
      {
        cyclomatic: 4,
        cyclomaticDensity: 66.667,
        halstead: {
          bugs: 0.077,
          difficulty: 7.594,
          effort: 1763.214,
          length: 50,
          time: 97.956,
          vocabulary: 25,
          volume: 232.193,
          operands: { distinct: 16, total: 27, identifiers: ["__stripped__"] },
          operators: { distinct: 9, total: 23, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 6, physical: 12 },
        errors: [],
        lineEnd: 41,
        lineStart: 30,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.009,
          difficulty: 1.875,
          effort: 52.638,
          length: 10,
          time: 2.924,
          vocabulary: 7,
          volume: 28.074,
          operands: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 5, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 47,
        lineStart: 44,
        name: "<anonymous>",
      },
      {
        cyclomatic: 4,
        cyclomaticDensity: 66.667,
        halstead: {
          bugs: 0.083,
          difficulty: 5.971,
          effort: 1478.246,
          length: 54,
          time: 82.125,
          vocabulary: 24,
          volume: 247.588,
          operands: { distinct: 17, total: 29, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 25, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 6, physical: 12 },
        errors: [],
        lineEnd: 61,
        lineStart: 50,
        name: "<anonymous>",
      },
      {
        cyclomatic: 6,
        cyclomaticDensity: 30,
        halstead: {
          bugs: 0.196,
          difficulty: 14.5,
          effort: 8522.558,
          length: 109,
          time: 473.475,
          vocabulary: 42,
          volume: 587.763,
          operands: { distinct: 28, total: 58, identifiers: ["__stripped__"] },
          operators: { distinct: 14, total: 51, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 20, physical: 43 },
        errors: [],
        lineEnd: 109,
        lineStart: 67,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 60,
        halstead: {
          bugs: 0.023,
          difficulty: 5,
          effort: 342.662,
          length: 18,
          time: 19.037,
          vocabulary: 14,
          volume: 68.532,
          operands: { distinct: 7, total: 10, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 8, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 5, physical: 10 },
        errors: [],
        lineEnd: 103,
        lineStart: 94,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 28.571,
        halstead: {
          bugs: 0.107,
          difficulty: 12,
          effort: 3864.273,
          length: 65,
          time: 214.682,
          vocabulary: 31,
          volume: 322.023,
          operands: { distinct: 19, total: 38, identifiers: ["__stripped__"] },
          operators: { distinct: 12, total: 27, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 7, physical: 12 },
        errors: [],
        lineEnd: 123,
        lineStart: 112,
        name: "<anonymous>",
      },
      {
        cyclomatic: 4,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.126,
          difficulty: 11.038,
          effort: 4170.959,
          length: 71,
          time: 231.72,
          vocabulary: 40,
          volume: 377.857,
          operands: { distinct: 26, total: 41, identifiers: ["__stripped__"] },
          operators: { distinct: 14, total: 30, identifiers: ["__stripped__"] },
        },
        params: 4,
        sloc: { logical: 8, physical: 16 },
        errors: [],
        lineEnd: 145,
        lineStart: 130,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.049,
          difficulty: 2.364,
          effort: 349.86,
          length: 40,
          time: 19.437,
          vocabulary: 13,
          volume: 148.018,
          operands: { distinct: 11, total: 26, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 14, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 4, physical: 6 },
        errors: [],
        lineEnd: 153,
        lineStart: 148,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 2.889,
      cyclomaticDensity: 45.582,
      halstead: {
        bugs: 0.078,
        difficulty: 7.1,
        effort: 2323.645,
        length: 49.444,
        time: 129.091,
        vocabulary: 23.222,
        volume: 235.073,
        operands: { distinct: 15.222, total: 27.778 },
        operators: { distinct: 8, total: 21.667 },
      },
      params: 1.889,
      sloc: { logical: 6.778, physical: 13.333 },
    },
    module: "src\\powerManager.js",
  },
  jshint: {
    messages: [
      {
        severity: "error",
        line: 94,
        column: 36,
        message:
          "Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. (conNum, pos, anyDir)",
        source:
          "Functions declared within loops referencing an outer scoped variable may lead to confusing semantics. ({a})",
      },
    ],
  },
};
