__report = {
  info: {
    file: "src\\debugWindow.js",
    fileShort: "src\\debugWindow.js",
    fileSafe: "src_debugWindow_js",
    link: "files/src_debugWindow_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 3,
      cyclomaticDensity: 9.677,
      halstead: {
        bugs: 0.383,
        difficulty: 16.681,
        effort: 19143.574,
        length: 192,
        time: 1063.532,
        vocabulary: 63,
        volume: 1147.638,
        operands: { distinct: 47, total: 98, identifiers: ["__stripped__"] },
        operators: { distinct: 16, total: 94, identifiers: ["__stripped__"] },
      },
      params: 4,
      sloc: { logical: 31, physical: 70 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./messages", type: "esm" },
      { line: 11, path: "./modalWindow", type: "esm" },
      { line: 12, path: "./miscUtils", type: "esm" },
    ],
    errors: [],
    lineEnd: 70,
    lineStart: 1,
    maintainability: 79.154,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.029,
          difficulty: 1.4,
          effort: 120.455,
          length: 24,
          time: 6.692,
          vocabulary: 12,
          volume: 86.039,
          operands: { distinct: 10, total: 14, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 10, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 17,
        lineStart: 14,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 66.667,
        halstead: {
          bugs: 0.018,
          difficulty: 4.5,
          effort: 239.179,
          length: 16,
          time: 13.288,
          vocabulary: 10,
          volume: 53.151,
          operands: { distinct: 5, total: 9, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 7, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 3, physical: 5 },
        errors: [],
        lineEnd: 29,
        lineStart: 25,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.009,
          difficulty: 1.875,
          effort: 52.638,
          length: 10,
          time: 2.924,
          vocabulary: 7,
          volume: 28.074,
          operands: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 5, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 35,
        lineStart: 32,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.061,
          difficulty: 5.7,
          effort: 1045.371,
          length: 40,
          time: 58.076,
          vocabulary: 24,
          volume: 183.399,
          operands: { distinct: 15, total: 19, identifiers: ["__stripped__"] },
          operators: { distinct: 9, total: 21, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 8, physical: 12 },
        errors: [],
        lineEnd: 49,
        lineStart: 38,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.003,
          difficulty: 1,
          effort: 8,
          length: 4,
          time: 0.444,
          vocabulary: 4,
          volume: 8,
          operands: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 54,
        lineStart: 52,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.007,
          difficulty: 2,
          effort: 39.303,
          length: 7,
          time: 2.183,
          vocabulary: 7,
          volume: 19.651,
          operands: { distinct: 3, total: 3, identifiers: ["__stripped__"] },
          operators: { distinct: 4, total: 4, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 8 },
        errors: [],
        lineEnd: 64,
        lineStart: 57,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.017,
          difficulty: 1.875,
          effort: 97.297,
          length: 15,
          time: 5.405,
          vocabulary: 11,
          volume: 51.891,
          operands: { distinct: 8, total: 10, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 5, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 63,
        lineStart: 60,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 1.286,
      cyclomaticDensity: 55.952,
      halstead: {
        bugs: 0.02,
        difficulty: 2.621,
        effort: 228.892,
        length: 16.571,
        time: 12.716,
        vocabulary: 10.714,
        volume: 61.458,
        operands: { distinct: 6.714, total: 8.857 },
        operators: { distinct: 4, total: 7.714 },
      },
      params: 0.571,
      sloc: { logical: 2.857, physical: 5.714 },
    },
    module: "src\\debugWindow.js",
  },
  jshint: { messages: [] },
};
