__report = {
  info: {
    file: "src\\inputStatus.js",
    fileShort: "src\\inputStatus.js",
    fileSafe: "src_inputStatus_js",
    link: "files/src_inputStatus_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 42,
      cyclomaticDensity: 21.538,
      halstead: {
        bugs: 3.306,
        difficulty: 59.981,
        effort: 594941.431,
        length: 1317,
        time: 33052.302,
        vocabulary: 185,
        volume: 9918.829,
        operands: { distinct: 158, total: 702, identifiers: ["__stripped__"] },
        operators: { distinct: 27, total: 615, identifiers: ["__stripped__"] },
      },
      params: 15,
      sloc: { logical: 195, physical: 308 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./eventEmitter", type: "esm" },
      { line: 11, path: "./gameCanvas", type: "esm" },
      { line: 12, path: "./gameTools", type: "esm" },
      { line: 13, path: "./messages", type: "esm" },
      { line: 14, path: "./miscUtils", type: "esm" },
    ],
    errors: [],
    lineEnd: 308,
    lineStart: 1,
    maintainability: 61.44,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 2.778,
        halstead: {
          bugs: 0.644,
          difficulty: 6.434,
          effort: 12425.163,
          length: 312,
          time: 690.287,
          vocabulary: 73,
          volume: 1931.225,
          operands: { distinct: 68, total: 175, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 137, identifiers: ["__stripped__"] },
        },
        params: 2,
        sloc: { logical: 36, physical: 54 },
        errors: [],
        lineEnd: 69,
        lineStart: 16,
        name: "<anonymous>",
      },
      {
        cyclomatic: 11,
        cyclomaticDensity: 40.741,
        halstead: {
          bugs: 0.125,
          difficulty: 8,
          effort: 2992.516,
          length: 77,
          time: 166.251,
          vocabulary: 29,
          volume: 374.065,
          operands: { distinct: 21, total: 42, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 35, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 27, physical: 36 },
        errors: [],
        lineEnd: 111,
        lineStart: 76,
        name: "<anonymous>",
      },
      {
        cyclomatic: 10,
        cyclomaticDensity: 52.632,
        halstead: {
          bugs: 0.078,
          difficulty: 3.75,
          effort: 882.095,
          length: 52,
          time: 49.005,
          vocabulary: 23,
          volume: 235.225,
          operands: { distinct: 18, total: 27, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 25, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 19, physical: 26 },
        errors: [],
        lineEnd: 139,
        lineStart: 114,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 25,
        halstead: {
          bugs: 0.05,
          difficulty: 5.231,
          effort: 781.157,
          length: 34,
          time: 43.398,
          vocabulary: 21,
          volume: 149.339,
          operands: { distinct: 13, total: 17, identifiers: ["__stripped__"] },
          operators: { distinct: 8, total: 17, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 4 },
        errors: [],
        lineEnd: 145,
        lineStart: 142,
        name: "<anonymous>",
      },
      {
        cyclomatic: 3,
        cyclomaticDensity: 42.857,
        halstead: {
          bugs: 0.073,
          difficulty: 6,
          effort: 1322.51,
          length: 51,
          time: 73.473,
          vocabulary: 20,
          volume: 220.418,
          operands: { distinct: 14, total: 28, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 23, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 7, physical: 11 },
        errors: [],
        lineEnd: 158,
        lineStart: 148,
        name: "<anonymous>",
      },
      {
        cyclomatic: 6,
        cyclomaticDensity: 46.154,
        halstead: {
          bugs: 0.205,
          difficulty: 11.367,
          effort: 7003.213,
          length: 115,
          time: 389.067,
          vocabulary: 41,
          volume: 616.118,
          operands: { distinct: 30, total: 62, identifiers: ["__stripped__"] },
          operators: { distinct: 11, total: 53, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 13, physical: 17 },
        errors: [],
        lineEnd: 177,
        lineStart: 161,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 20,
        halstead: {
          bugs: 0.041,
          difficulty: 2.833,
          effort: 351.333,
          length: 31,
          time: 19.519,
          vocabulary: 16,
          volume: 124,
          operands: { distinct: 12, total: 17, identifiers: ["__stripped__"] },
          operators: { distinct: 4, total: 14, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 5, physical: 7 },
        errors: [],
        lineEnd: 186,
        lineStart: 180,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 20,
        halstead: {
          bugs: 0.102,
          difficulty: 5.938,
          effort: 1825.557,
          length: 70,
          time: 101.42,
          vocabulary: 21,
          volume: 307.462,
          operands: { distinct: 16, total: 38, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 32, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 10, physical: 17 },
        errors: [],
        lineEnd: 205,
        lineStart: 189,
        name: "<anonymous>",
      },
      {
        cyclomatic: 4,
        cyclomaticDensity: 28.571,
        halstead: {
          bugs: 0.167,
          difficulty: 14.474,
          effort: 7242.227,
          length: 103,
          time: 402.346,
          vocabulary: 29,
          volume: 500.372,
          operands: { distinct: 19, total: 55, identifiers: ["__stripped__"] },
          operators: { distinct: 10, total: 48, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 14, physical: 20 },
        errors: [],
        lineEnd: 227,
        lineStart: 208,
        name: "<anonymous>",
      },
      {
        cyclomatic: 9,
        cyclomaticDensity: 150,
        halstead: {
          bugs: 0.103,
          difficulty: 8.889,
          effort: 2734.851,
          length: 64,
          time: 151.936,
          vocabulary: 28,
          volume: 307.671,
          operands: { distinct: 18, total: 32, identifiers: ["__stripped__"] },
          operators: { distinct: 10, total: 32, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 6, physical: 8 },
        errors: [],
        lineEnd: 237,
        lineStart: 230,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 13.333,
        halstead: {
          bugs: 0.224,
          difficulty: 8.875,
          effort: 5963.433,
          length: 131,
          time: 331.302,
          vocabulary: 35,
          volume: 671.936,
          operands: { distinct: 28, total: 71, identifiers: ["__stripped__"] },
          operators: { distinct: 7, total: 60, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 15, physical: 27 },
        errors: [],
        lineEnd: 266,
        lineStart: 240,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.014,
          difficulty: 1.333,
          effort: 56,
          length: 14,
          time: 3.111,
          vocabulary: 8,
          volume: 42,
          operands: { distinct: 6, total: 8, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 6, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 245,
        lineStart: 242,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.047,
          difficulty: 4.75,
          effort: 673.443,
          length: 34,
          time: 37.413,
          vocabulary: 18,
          volume: 141.777,
          operands: { distinct: 12, total: 19, identifiers: ["__stripped__"] },
          operators: { distinct: 6, total: 15, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 4, physical: 6 },
        errors: [],
        lineEnd: 274,
        lineStart: 269,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 28.571,
        halstead: {
          bugs: 0.068,
          difficulty: 3.824,
          effort: 784.335,
          length: 46,
          time: 43.574,
          vocabulary: 22,
          volume: 205.134,
          operands: { distinct: 17, total: 26, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 20, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 7, physical: 11 },
        errors: [],
        lineEnd: 287,
        lineStart: 277,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.011,
          difficulty: 3.125,
          effort: 99.06,
          length: 10,
          time: 5.503,
          vocabulary: 9,
          volume: 31.699,
          operands: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 5, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 2, physical: 7 },
        errors: [],
        lineEnd: 296,
        lineStart: 290,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 100,
        halstead: {
          bugs: 0.005,
          difficulty: 1,
          effort: 15.51,
          length: 6,
          time: 0.862,
          vocabulary: 6,
          volume: 15.51,
          operands: { distinct: 4, total: 4, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 2, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 1, physical: 3 },
        errors: [],
        lineEnd: 295,
        lineStart: 293,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 3.563,
      cyclomaticDensity: 45.04,
      halstead: {
        bugs: 0.122,
        difficulty: 5.989,
        effort: 2822.025,
        length: 71.875,
        time: 156.779,
        vocabulary: 24.938,
        volume: 367.122,
        operands: { distinct: 18.75, total: 39.125 },
        operators: { distinct: 6.188, total: 32.75 },
      },
      params: 0.938,
      sloc: { logical: 10.75, physical: 16.125 },
    },
    module: "src\\inputStatus.js",
  },
  jshint: { messages: [] },
};
