__report = {
  info: {
    file: "src\\settingsWindow.js",
    fileShort: "src\\settingsWindow.js",
    fileSafe: "src_settingsWindow_js",
    link: "files/src_settingsWindow_js/index.html",
  },
  complexity: {
    methodAggregate: {
      cyclomatic: 10,
      cyclomaticDensity: 11.765,
      halstead: {
        bugs: 1.002,
        difficulty: 23.865,
        effort: 71755.266,
        length: 446,
        time: 3986.404,
        vocabulary: 107,
        volume: 3006.694,
        operands: { distinct: 89, total: 236, identifiers: ["__stripped__"] },
        operators: { distinct: 18, total: 210, identifiers: ["__stripped__"] },
      },
      params: 5,
      sloc: { logical: 85, physical: 124 },
    },
    settings: {
      commonjs: true,
      forin: false,
      logicalor: true,
      switchcase: true,
      trycatch: false,
      newmi: true,
    },
    classes: [],
    dependencies: [
      { line: 10, path: "./messages", type: "esm" },
      { line: 11, path: "./modalWindow", type: "esm" },
      { line: 12, path: "./miscUtils", type: "esm" },
      { line: 13, path: "./simulation", type: "esm" },
    ],
    errors: [],
    lineEnd: 124,
    lineStart: 1,
    maintainability: 63.971,
    methods: [
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.029,
          difficulty: 1.4,
          effort: 120.455,
          length: 24,
          time: 6.692,
          vocabulary: 12,
          volume: 86.039,
          operands: { distinct: 10, total: 14, identifiers: ["__stripped__"] },
          operators: { distinct: 2, total: 10, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 18,
        lineStart: 15,
        name: "<anonymous>",
      },
      {
        cyclomatic: 2,
        cyclomaticDensity: 66.667,
        halstead: {
          bugs: 0.018,
          difficulty: 4.5,
          effort: 239.179,
          length: 16,
          time: 13.288,
          vocabulary: 10,
          volume: 53.151,
          operands: { distinct: 5, total: 9, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 7, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 3, physical: 5 },
        errors: [],
        lineEnd: 39,
        lineStart: 35,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.009,
          difficulty: 1.875,
          effort: 52.638,
          length: 10,
          time: 2.924,
          vocabulary: 7,
          volume: 28.074,
          operands: { distinct: 4, total: 5, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 5, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 45,
        lineStart: 42,
        name: "<anonymous>",
      },
      {
        cyclomatic: 4,
        cyclomaticDensity: 12.903,
        halstead: {
          bugs: 0.24,
          difficulty: 14.259,
          effort: 10251.924,
          length: 137,
          time: 569.551,
          vocabulary: 38,
          volume: 718.966,
          operands: { distinct: 27, total: 70, identifiers: ["__stripped__"] },
          operators: { distinct: 11, total: 67, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 31, physical: 31 },
        errors: [],
        lineEnd: 78,
        lineStart: 48,
        name: "<anonymous>",
      },
      {
        cyclomatic: 6,
        cyclomaticDensity: 30,
        halstead: {
          bugs: 0.176,
          difficulty: 6.739,
          effort: 3563.713,
          length: 110,
          time: 197.984,
          vocabulary: 28,
          volume: 528.809,
          operands: { distinct: 23, total: 62, identifiers: ["__stripped__"] },
          operators: { distinct: 5, total: 48, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 20, physical: 25 },
        errors: [],
        lineEnd: 105,
        lineStart: 81,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.007,
          difficulty: 2,
          effort: 39.303,
          length: 7,
          time: 2.183,
          vocabulary: 7,
          volume: 19.651,
          operands: { distinct: 3, total: 3, identifiers: ["__stripped__"] },
          operators: { distinct: 4, total: 4, identifiers: ["__stripped__"] },
        },
        params: 0,
        sloc: { logical: 2, physical: 8 },
        errors: [],
        lineEnd: 115,
        lineStart: 108,
        name: "<anonymous>",
      },
      {
        cyclomatic: 1,
        cyclomaticDensity: 50,
        halstead: {
          bugs: 0.017,
          difficulty: 1.875,
          effort: 97.297,
          length: 15,
          time: 5.405,
          vocabulary: 11,
          volume: 51.891,
          operands: { distinct: 8, total: 10, identifiers: ["__stripped__"] },
          operators: { distinct: 3, total: 5, identifiers: ["__stripped__"] },
        },
        params: 1,
        sloc: { logical: 2, physical: 4 },
        errors: [],
        lineEnd: 114,
        lineStart: 111,
        name: "<anonymous>",
      },
    ],
    methodAverage: {
      cyclomatic: 2.286,
      cyclomaticDensity: 44.224,
      halstead: {
        bugs: 0.071,
        difficulty: 4.664,
        effort: 2052.073,
        length: 45.571,
        time: 114.004,
        vocabulary: 16.143,
        volume: 212.369,
        operands: { distinct: 11.429, total: 24.714 },
        operators: { distinct: 4.714, total: 20.857 },
      },
      params: 0.714,
      sloc: { logical: 8.857, physical: 11.571 },
    },
    module: "src\\settingsWindow.js",
  },
  jshint: { messages: [] },
};
